import test from 'node:test';
import assert from 'node:assert/strict';
import {makeSeed} from '../server/seed.mjs';
import {act,record,visibleState,upload,canReadFile,usage} from '../server/domain.mjs';
import {initializePlatform,providerPrincipal,providerIdentity,effectivePlan,catalogPlans,seatUsage} from '../server/access.mjs';
import {providerAction,providerState,acceptInvitation,invitationInfo} from '../server/provider.mjs';
import {createAppServer} from '../server/server.mjs';
const setup=()=>{const s=initializePlatform(makeSeed()),identity=s.providerAccounts[0];return{s,identity,p:providerPrincipal(s,identity,'vayu','test-session'),admin:s.users[0],member:s.users[1]};};
const png={name:'private.png',mime:'image/png',data:Buffer.from([137,80,78,71,13,10,26,10,1]).toString('base64')};
const invite=(s,u,email='invite@example.test',role='member')=>act(s,u,{action:'invitation.create',data:{name:'Invited Employee',email,role}});

test('platform migration preserves organizations and has stable plans and provider identities',()=>{const s=makeSeed(),original=JSON.stringify(s.artworks);initializePlatform(s);const ids=s.planVersions.map(p=>p.id);initializePlatform(s);assert.equal(JSON.stringify(s.artworks),original);assert.equal(s.providerAccounts.length,1);assert.deepEqual(s.planVersions.map(p=>p.id),ids);assert.equal(s.workspaces[0].ownerId,'admin');assert.equal(s.users.some(u=>u.id==='provider-owner'),false);});
test('provider creates an empty organization with an owner on its selected plan',()=>{const{s,identity}=setup();const w=providerAction(s,identity,{action:'organization.create',data:{name:'Fresh Studio',ownerName:'New Owner',email:'fresh@example.test',plan:'Studio',kind:'Studio'}});const owner=s.users.find(u=>u.id===w.ownerId);assert.equal(owner.workspaceId,w.id);assert.equal(owner.role,'admin');assert.equal(effectivePlan(s,w).name,'Studio');assert.equal(visibleState(s,owner).artworks.length,0);assert.equal(usage(s,owner).seats,1);assert.equal(s.audit.at(-1).actorType,'provider');});
test('provider accesses private rooms and files without consuming seats or joining rooms',()=>{const{s,p,admin,member}=setup(),before=usage(s,p).seats,f=upload(s,member,png);act(s,member,{action:'message.send',entity:'rooms',entityId:'room2',data:{text:'Private attachment',fileId:f.id}});assert.equal(canReadFile(s,admin,f.id),false);assert.equal(canReadFile(s,p,f.id),true);assert.equal(visibleState(s,p).rooms.length,2);assert.equal(usage(s,p).seats,before);assert.equal(s.rooms.some(r=>r.memberIds.includes(p.id)),false);assert.throws(()=>record(s,{...admin,provider:true,isSuperAdmin:true},'rooms','room2'),/not a participant/);});
test('provider writes retain provider attribution and remain scoped to the selected organization',()=>{const{s,p}=setup();act(s,p,{action:'save',entity:'artworks',entityId:'a1',data:{title:'Provider update',workspaceId:'other'}});const event=s.audit.at(-1);assert.equal(event.actorId,'provider-owner');assert.equal(event.actorType,'provider');assert.equal(event.providerAccessId,'test-session');assert.equal(event.workspaceId,'vayu');assert.throws(()=>record(s,providerPrincipal(s,s.providerAccounts[0],'other','next'),'artworks','a1'),/not found/);});
test('provider edits retain message authors and revisions without leaking bodies into audit',()=>{const{s,p,member,admin}=setup();const m=act(s,member,{action:'message.send',entity:'rooms',entityId:'room2',data:{text:'Original private text'}});act(s,p,{action:'message.edit',entity:'rooms',entityId:'room2',data:{messageId:m.id,text:'Corrected private text'}});assert.equal(m.senderId,member.id);assert.equal(m.providerEditedBy,p.id);assert.equal(s.messageRevisions.at(-1).text,'Original private text');assert.equal(visibleState(s,p).messageRevisions.length,1);assert.equal(visibleState(s,member).messageRevisions.length,0);assert.equal(JSON.stringify(s.audit).includes('Original private text'),false);assert.equal(JSON.stringify(s.audit).includes('Corrected private text'),false);const event=visibleState(s,admin).audit.find(e=>e.entityId===m.id);assert.equal(event,undefined);});
test('provider messages identify their sender and do not create fake customer read receipts',()=>{const{s,p}=setup();const m=act(s,p,{action:'message.send',entity:'rooms',entityId:'room2',data:{text:'Provider notice'}});assert.equal(m.senderType,'provider');assert.equal(m.senderName,'Vayu Provider');const before=structuredClone(s.messages.map(m=>m.readBy));act(s,p,{action:'message.read',entity:'rooms',entityId:'room2'});assert.deepEqual(s.messages.map(m=>m.readBy),before);});
test('private attachment revisions survive catalog purge without reopening uploader access',()=>{const{s,p,member}=setup();const file=upload(s,member,{name:'private.pdf',mime:'application/pdf',data:Buffer.from('%PDF-1.4 sample').toString('base64')});const m=act(s,member,{action:'message.send',entity:'rooms',entityId:'room2',data:{text:'Private version',fileId:file.id}});act(s,p,{action:'catalog.version',entityId:'cat1',data:{fileId:file.id}});act(s,p,{action:'message.delete',entity:'rooms',entityId:'room2',data:{messageId:m.id}});act(s,p,{action:'trash',entity:'catalogs',entityId:'cat1'});act(s,p,{action:'purge',entity:'catalogs',entityId:'cat1'});assert.ok(s.files.some(f=>f.id===file.id));assert.equal(canReadFile(s,member,file.id),false);assert.equal(canReadFile(s,p,file.id),true);});
test('suspension blocks organization reads and writes while retaining provider management',()=>{const{s,p,admin,identity}=setup();providerAction(s,identity,{action:'organization.update',entityId:'vayu',data:{status:'suspended',reason:'Account review'}});assert.equal(visibleState(s,admin).artworks.length,0);assert.throws(()=>act(s,admin,{action:'membership.change',data:{plan:'Business'}}),/suspended/);assert.equal(visibleState(s,p).artworks.length,6);act(s,p,{action:'save',entity:'artworks',entityId:'a1',data:{title:'Provider correction'}});assert.equal(s.artworks[0].title,'Provider correction');});
test('new plan versions preserve existing subscriptions until reassigned',()=>{const{s,identity}=setup(),w=s.workspaces[0],old=effectivePlan(s,w);const plan=providerAction(s,identity,{action:'plan.save',entityId:old.id,data:{...old,seats:99,reason:'New package'}});assert.equal(plan.version,2);assert.equal(effectivePlan(s,w).seats,30);assert.equal(catalogPlans(s).Business.seats,99);providerAction(s,identity,{action:'organization.update',entityId:w.id,data:{planVersionId:plan.id,reason:'Upgrade package'}});assert.equal(effectivePlan(s,w).seats,99);});
test('organization-specific allowances expire and provider work still obeys cost quotas',()=>{const{s,p,identity}=setup(),w=s.workspaces[0];providerAction(s,identity,{action:'organization.update',entityId:w.id,data:{limits:{seats:2,artworks:6},reason:'Custom allowance'}});assert.throws(()=>invite(s,p),/limit/);assert.throws(()=>act(s,p,{action:'save',entity:'artworks',data:{title:'Over quota',price:1}}),/limit/);w.allowanceOverride.expiresAt=new Date(Date.now()-1000).toISOString();assert.equal(effectivePlan(s,w).seats,30);});
test('invitations reserve seats, expose the token once, and release reservations on cancellation',()=>{const{s,admin}=setup();s.workspaces[0].allowanceOverride={limits:{seats:3}};const i=invite(s,admin);assert.equal(usage(s,admin).seats,3);assert.throws(()=>invite(s,admin,'second@example.test'),/limit/);assert.equal(visibleState(s,admin).invitations[0].tokenHash,undefined);assert.equal(JSON.stringify(s).includes(i.token),false);act(s,admin,{action:'invitation.cancel',entityId:i.id});assert.equal(usage(s,admin).seats,2);assert.throws(()=>acceptInvitation(s,i.token),/expired/);});
test('invitation acceptance converts a reservation exactly once and retains its organization and role',()=>{const{s,admin}=setup(),i=invite(s,admin),before=usage(s,admin).seats;const user=acceptInvitation(s,i.token);assert.equal(user.workspaceId,'vayu');assert.equal(user.role,'member');assert.equal(usage(s,admin).seats,before);assert.equal(seatUsage(s,'vayu').reserved,0);assert.throws(()=>acceptInvitation(s,i.token),/already been used/);});
test('expiry, downgrade and suspension are rechecked when accepting an invitation',()=>{const{s,admin}=setup(),i=invite(s,admin);s.workspaces[0].allowanceOverride={limits:{seats:2}};assert.throws(()=>acceptInvitation(s,i.token),/allowance/);delete s.workspaces[0].allowanceOverride;s.workspaces[0].status='suspended';assert.throws(()=>invitationInfo(s,i.token),/cannot accept/);s.workspaces[0].status='active';s.invitations[0].expiresAt=new Date(Date.now()-1).toISOString();assert.throws(()=>acceptInvitation(s,i.token),/expired/);});
test('guest invitation limits and reactivating employees are enforced',()=>{const{s,admin}=setup();s.workspaces[0].allowanceOverride={limits:{guests:1,seats:2}};assert.throws(()=>invite(s,admin,'guest2@example.test','guest'),/guest limit/);act(s,admin,{action:'member.update',entityId:'member',data:{role:'member',disabled:true}});invite(s,admin);assert.throws(()=>act(s,admin,{action:'member.update',entityId:'member',data:{role:'member',disabled:false}}),/limit/);});
test('ownership cannot be removed accidentally and provider can transfer it to an active admin',()=>{const{s,p,admin}=setup();assert.throws(()=>act(s,p,{action:'member.update',entityId:admin.id,data:{role:'member',disabled:true}}),/Transfer organization ownership/);act(s,p,{action:'member.update',entityId:'member',data:{role:'admin',disabled:false}});act(s,p,{action:'organization.transfer',data:{ownerId:'member'}});assert.equal(s.workspaces[0].ownerId,'member');act(s,p,{action:'member.update',entityId:admin.id,data:{role:'member',disabled:false}});assert.equal(admin.role,'member');});
test('provider drafts are scoped independently for each organization',()=>{const{s,p,identity}=setup();act(s,p,{action:'draft.save',entity:'catalogs',data:{title:'First organization'}});const other=providerPrincipal(s,identity,'other','other-scope');act(s,other,{action:'draft.save',entity:'catalogs',data:{title:'Second organization'}});assert.equal(visibleState(s,p).drafts[0].data.title,'First organization');assert.equal(visibleState(s,other).drafts[0].data.title,'Second organization');});
test('only the provider owner manages provider admins and role revocation blocks new principals',()=>{const{s,identity,admin}=setup();assert.throws(()=>providerState(s,admin),/Provider access/);const added=providerAction(s,identity,{action:'provider.add',data:{name:'Support Admin',email:'support@example.test'}});assert.throws(()=>providerAction(s,added,{action:'provider.add',data:{name:'No',email:'no@example.test'}}),/Only the provider owner/);providerAction(s,identity,{action:'provider.update',entityId:added.id,data:{disabled:true}});assert.equal(providerIdentity(s,added.id),undefined);assert.equal(providerPrincipal(s,added,'vayu','revoked'),null);});

async function serverFixture(t){const server=createAppServer({memory:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base=`http://127.0.0.1:${server.address().port}`;const client=()=>{let cookie='',scope='';const request=async(path,body,extra={})=>{const r=await fetch(`${base}/api/${path}`,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(cookie?{cookie}:{}),...(scope?{'X-Vayu-Context':scope}:{}),...extra},body:body===undefined?undefined:JSON.stringify(body)});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];if(r.headers.get('content-type')?.includes('json')){const j=await r.clone().json();scope=j.apiScope||j.state?.apiScope||scope;}return r;};return{request,getScope:()=>scope};};return{client};}
test('HTTP customer identities cannot invoke provider APIs or forge provider access',async t=>{const f=await serverFixture(t),c=f.client();await c.request('login',{userId:'admin'});assert.equal((await c.request('provider/state')).status,403);assert.equal((await c.request('provider/enter',{workspaceId:'other',provider:true})).status,403);assert.equal((await c.request('action',{action:'save',entity:'rooms',entityId:'room2',data:{title:'Unauthorized',provider:true}})).status,403);assert.equal((await c.request('provider/login',{userId:'admin'})).status,404);});
test('HTTP provider changes organizations without leaking old data or accepting stale writes',async t=>{const f=await serverFixture(t),c=f.client();await c.request('provider/login',{userId:'provider-owner'});assert.equal((await(await c.request('state')).json()).kind,'provider');const entered=await(await c.request('provider/enter',{workspaceId:'vayu'})).json();assert.equal(entered.state.rooms.length,2);const stale=c.getScope();await c.request('provider/enter',{workspaceId:'other'});assert.equal((await c.request('action',{action:'save',entity:'artworks',data:{title:'Stale draft',price:1}},{'X-Vayu-Context':stale})).status,409);const s=await(await c.request('state')).json();assert.equal(s.workspace.id,'other');assert.equal(s.artworks.length,0);assert.equal((await c.request('action',{action:'save',entity:'artworks',entityId:'a1',data:{title:'Wrong organization'}})).status,404);await c.request('provider/exit',{});assert.equal((await(await c.request('state')).json()).kind,'provider');});
test('HTTP concurrent invitations cannot exceed the last available seat',async t=>{const f=await serverFixture(t),p=f.client(),owner=f.client();await p.request('provider/login',{userId:'provider-owner'});await p.request('state');await p.request('provider/action',{action:'organization.update',entityId:'vayu',data:{limits:{seats:3},reason:'Seat boundary test'}});await owner.request('login',{userId:'admin'});const results=await Promise.all(['one','two','three'].map(n=>owner.request('action',{action:'invitation.create',data:{name:n,email:`${n}@example.test`,role:'member'}})));assert.deepEqual(results.map(r=>r.status).sort(),[200,409,409]);const s=await(await owner.request('state')).json();assert.equal(s.usage.seats,3);assert.equal(s.invitations.length,1);});
test('HTTP invitation redemption ignores injected roles and cannot be replayed',async t=>{const f=await serverFixture(t),a=f.client(),join=f.client();await a.request('login',{userId:'admin'});const i=await(await a.request('action',{action:'invitation.create',data:{name:'Employee',email:'employee@example.test',role:'member'}})).json();assert.equal((await join.request('invitation/accept',{token:i.result.token,role:'admin',workspaceId:'other'})).status,200);const s=await(await join.request('state')).json();assert.equal(s.user.role,'member');assert.equal(s.workspace.id,'vayu');assert.equal((await join.request('invitation/accept',{token:i.result.token})).status,404);});
test('HTTP invalid provider updates roll back and disabled provider sessions lose access',async t=>{const f=await serverFixture(t),p=f.client(),staff=f.client();await p.request('provider/login',{userId:'provider-owner'});await p.request('state');const bad=await p.request('provider/action',{action:'organization.update',entityId:'vayu',data:{name:'Should roll back',status:'invalid',reason:'Test'}});assert.equal(bad.status,400);assert.equal((await(await p.request('state')).json()).organizations[0].name,'Vayu Gallery');const created=await(await p.request('provider/action',{action:'provider.add',data:{name:'Support',email:'support@example.test'}})).json();await staff.request('provider/login',{userId:created.result.id});await staff.request('state');await staff.request('provider/enter',{workspaceId:'vayu'});await p.request('provider/action',{action:'provider.update',entityId:created.result.id,data:{disabled:true}});assert.equal((await staff.request('state')).status,401);});
