import test from 'node:test';
import assert from 'node:assert/strict';
import {createAppServer} from '../server/server.mjs';
async function fixture(t){const server=createAppServer({memory:true});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base=`http://127.0.0.1:${server.address().port}`;let cookie='';const request=async(path,body,extra={})=>{const r=await fetch(base+'/api/'+path,{method:body===undefined?'GET':'POST',headers:{...body?{'Content-Type':'application/json'}:{},...cookie?{cookie}:{},...extra},body:body===undefined?undefined:JSON.stringify(body)});const set=r.headers.get('set-cookie');if(set)cookie=set.split(';')[0];return r;};const login=id=>request('login',{userId:id});return{request,login,base};}
test('HTTP sessions require login and do not expose private storage in JSON',async t=>{const f=await fixture(t);assert.equal((await f.request('state')).status,401);await f.login('admin');const s=await(await f.request('state')).json();assert.equal(s.user.id,'admin');assert.equal(s.rooms.length,1);assert.equal(s.workspaces,undefined);await f.request('logout',{});assert.equal((await f.request('state')).status,401);});
test('HTTP rejects cross-origin changes',async t=>{const f=await fixture(t);await f.login('admin');assert.equal((await f.request('action',{action:'membership.cancel'},{origin:'https://untrusted.invalid'})).status,403);const s=await(await f.request('state')).json();assert.equal(s.workspace.subscription,'active');});
test('failed bulk import is atomic and leaves an audit rejection',async t=>{const f=await fixture(t);await f.login('admin');const r=await f.request('action',{action:'bulk.import',data:{rows:[{title:'Valid',price:100},{title:'',price:10}]}});assert.equal(r.status,400);const s=await(await f.request('state')).json();assert.equal(s.artworks.length,6);assert.equal(s.audit[0].outcome,'failed');});
test('multi-item payment failure rolls back every artwork and accounting change',async t=>{const f=await fixture(t);await f.login('admin');const inv=await(await f.request('action',{action:'save',entity:'invoices',data:{title:'Atomic test',customerId:'c2',artworkIds:['a1','a2'],taxRate:0,sellerAddress:'Gallery address, Mumbai'}})).json();assert.equal((await f.request('action',{action:'invoice.issue',entityId:inv.result.id})).status,200);const pay=await(await f.request('action',{action:'save',entity:'payments',data:{title:'Atomic pay',invoiceId:inv.result.id}})).json();const r=await f.request('action',{action:'payment.simulate',entityId:pay.result.id});assert.equal(r.status,409);const s=await(await f.request('state')).json();assert.equal(s.artworks.find(a=>a.id==='a1').status,'Available');assert.equal(s.payments.find(p=>p.id===pay.result.id).status,'Pending');});
test('share links expire/revoke, are file-scoped, and original API paths do not exist',async t=>{const f=await fixture(t);await f.login('admin');const file=await(await f.request('upload',{name:'test.pdf',mime:'application/pdf',data:Buffer.from('%PDF-1.4\n sample').toString('base64')})).json();await f.request('action',{action:'catalog.version',entityId:'cat1',data:{fileId:file.id}});const share=await(await f.request('action',{action:'share.create',entityId:'cat1',data:{days:1}})).json();const url=f.base+'/api/shared/'+share.result.token;assert.equal((await fetch(url)).status,200);await f.request('action',{action:'share.revoke',entityId:share.result.id});assert.equal((await fetch(url)).status,404);assert.equal((await f.request('auth/setup')).status,404);});
test('member cannot export records or access backups',async t=>{const f=await fixture(t);await f.login('member');assert.equal((await f.request('export')).status,403);assert.equal((await f.request('backups')).status,403);});
test('public local membership flow creates isolated pending workspace',async t=>{const f=await fixture(t);const r=await f.request('register',{name:'New Sample',email:'new@example.test',workspace:'New space',plan:'Studio'});assert.equal(r.status,200);let s=await(await f.request('state')).json();assert.equal(s.workspace.subscription,'pending');assert.equal(s.artworks.length,0);assert.equal(s.users.length,1);await f.request('action',{action:'membership.change',data:{plan:'Studio'}});s=await(await f.request('state')).json();assert.equal(s.workspace.subscription,'active');});
test('concurrent writes retain every record and audit event',async t=>{const f=await fixture(t);await f.login('admin');const results=await Promise.all(Array.from({length:12},(_,i)=>f.request('action',{action:'save',entity:'artworks',data:{title:`Concurrent ${i}`,price:10+i}})));assert.ok(results.every(r=>r.status===200));const s=await(await f.request('state')).json();assert.equal(s.artworks.length,18);assert.equal(s.audit.filter(e=>e.action==='artworks.created').length,12);});
