const escape=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderWebsite(site:{gallery:string;slug:string;content:{pages:any[];artworks:any[]}},pageSlug:string,origin:string) {
 const page=site.content.pages.find(p=>p.slug===pageSlug)||(!pageSlug?site.content.pages[0]:null);
 if(!page)return null;
 const works=site.content.artworks;
 const cards=works.map(a=>`<article>${a.imageId?`<img src="/api/public/sites/${escape(site.slug)}/media/${escape(a.imageId)}" alt="${escape(a.title)}" loading="lazy" width="640" height="640">`:''}<h3>${escape(a.title)}</h3><p>${escape(a.artist)}</p><p>${escape(a.medium)}</p>${a.priceMinor!==null?`<p>${escape(new Intl.NumberFormat('en',{style:'currency',currency:a.currency}).format(Number(a.priceMinor)/10**new Intl.NumberFormat('en',{style:'currency',currency:a.currency}).resolvedOptions().maximumFractionDigits!))}</p>`:''}</article>`).join('');
 const content=page.content.map((b:any)=>b.type==='heading'?`<h1>${escape(b.text)}</h1>`:b.type==='paragraph'?`<p class="prose">${escape(b.text)}</p>`:b.type==='artworks'?`<h2>${escape(b.title)}</h2><div class="grid">${cards}</div>`:'').join('');
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(page.seo?.title||page.title)} · ${escape(site.gallery)}</title><meta name="description" content="${escape(page.seo?.description||'')}"><link rel="canonical" href="${escape(origin)}/site/${escape(site.slug)}/${escape(page.slug)}"><meta property="og:title" content="${escape(page.seo?.title||page.title)}"><meta property="og:description" content="${escape(page.seo?.description||'')}"><meta property="og:type" content="website"><style>body{margin:0;background:#faf9f6;color:#26372d;font:17px/1.65 Georgia,serif}header,main,footer{max-width:1160px;margin:auto;padding:32px 24px}header{display:flex;justify-content:space-between;gap:24px;flex-wrap:wrap;border-bottom:1px solid #ddd}nav{display:flex;gap:20px;flex-wrap:wrap}a{color:inherit;text-underline-offset:5px}h1{font-weight:400;font-size:clamp(40px,7vw,76px);line-height:1.1;max-width:900px}h2{font-size:32px;font-weight:400;margin-top:60px}.prose{max-width:750px;white-space:pre-wrap}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:40px}article img{width:100%;height:auto;aspect-ratio:1;object-fit:contain;background:#f1eee6}article h3{margin:16px 0 4px}article p{margin:4px 0;font-size:15px}footer{margin-top:80px;border-top:1px solid #ddd}@media(prefers-reduced-motion:no-preference){article{animation:enter .5s ease both}@keyframes enter{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}}</style></head><body><header><strong>${escape(site.gallery)}</strong><nav aria-label="Gallery pages">${site.content.pages.map(p=>`<a href="/site/${escape(site.slug)}/${escape(p.slug)}">${escape(p.title)}</a>`).join('')}</nav></header><main>${content}</main><footer>${escape(site.gallery)}</footer></body></html>`;
}
