import React,{useEffect,useState,useRef} from 'react';
import { LayoutDashboard, Images, Layers, BookOpen, Users, MessageCircle, LockKeyhole, ClipboardList, Receipt, Wallet, Truck, ChartNoAxesCombined, Bell, Search, Plus, ChevronDown, ArrowUpRight, ArrowRight, Check, X, Menu, Settings, Activity, CreditCard, LogOut, Sparkles, CircleHelp, ListTodo, Archive, ShieldCheck, Leaf } from 'lucide-react';
import { Context, api, go, useRoute, Button, Avatar, Modal, Badge, money, label, Empty } from './lib.jsx';
import { Overview, Inventory, Collections, Catalogs, CatalogStudio } from './art.jsx';
import { Records, Reports, RecordDetail } from './business.jsx';
import { Collaboration } from './collaboration.jsx';
import { Membership, BillingEvents, Administration, ActivityLog, Trash } from './admin.jsx';
import { EntityForm } from './forms.jsx';
import {ProviderConsole,InvitationLanding} from './provider.jsx';
import './refinements.css';

const nav=[
 ['overview','Overview',LayoutDashboard,''],
 ['artworks','Inventory',Images,'ART & CONTENT'],['collections','Collections',Layers,''],['catalogs','Catalog',BookOpen,''],
 ['inquiries','Inquiries',ClipboardList,'RELATIONSHIPS'],['customers','Customers',Users,''],['tasks','Follow-ups',ListTodo,''],['conversations','Messages',MessageCircle,''],['rooms','Private rooms',LockKeyhole,''],
 ['reservations','Reservations',Archive,'BUSINESS'],['invoices','Invoices',Receipt,''],['payments','Payments',Wallet,''],['deliveries','Deliveries',Truck,''],['reports','Reports',ChartNoAxesCombined,''],
 ['audit','Activity log',Activity,'ADMINISTRATION'],['membership','Membership',CreditCard,''],['settings','Team & settings',Settings,''],['trash','Trash',Archive,'']
];
class Boundary extends React.Component{state={error:null};static getDerivedStateFromError(error){return {error};}render(){return this.state.error?<div className="empty"><h2>Something interrupted this screen</h2><p>Your saved data is still in the local service.</p><button className="button" onClick={()=>location.reload()}>Reload workspace</button></div>:this.props.children;}}
export default function App(){
 const[session,setSession]=useState(null),[state,setState]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notices,setNotices]=useState([]);const route=useRoute();
 const toast=(text,type='success')=>{const id=Date.now()+Math.random();setNotices(n=>[...n,{id,text,type}]);setTimeout(()=>setNotices(n=>n.filter(x=>x.id!==id)),5000);};
 const refresh=async()=>{try{const s=await api('state');setState(s);return s;}catch(e){if(e.status===401){setState(null);setSession(await api('session'));}throw e;}};
 const load=async()=>{setError('');try{const s=await api('session');setSession(s);if(s.user)await refresh();else setState(null);}catch(e){setError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(!state?.user)return;const tick=setInterval(()=>{if(document.visibilityState==='visible')refresh().catch(()=>{});},10000);return()=>clearInterval(tick);},[state?.user.id]);
 const mutate=async(input,message)=>{try{const r=await api('action',input);setState(r.state);if(message)toast(message);return r.result;}catch(e){toast(e.message,'error');return null;}};
 const login=async id=>{try{await api('login',{userId:id});await load();go(id==='client'?'rooms':'overview');}catch(e){toast(e.message,'error');}};
 const providerLogin=async userId=>{try{await api('provider/login',{userId});setLoading(true);setState(null);await load();go('provider');}catch(e){toast(e.message,'error');setLoading(false);}};
 const providerMutate=async(input,message)=>{try{const r=await api('provider/action',input);setState(r.state);if(message)toast(message);return r.result;}catch(e){toast(e.message,'error');return null;}};
 const openOrganization=async workspaceId=>{try{const r=await api('provider/enter',{workspaceId});setState(r.state);go('overview');}catch(e){toast(e.message,'error');}};
 const closeOrganization=async()=>{try{const r=await api('provider/exit',{});setState(r.state);go('provider');}catch(e){toast(e.message,'error');}};
 const logout=async()=>{await api('logout',{});setState(null);await load();};
 const context={state,session,refresh,mutate,providerMutate,providerLogin,openOrganization,closeOrganization,toast,route,login,logout,load};
 return <Context.Provider value={context}><Boundary>{loading?<div className="loading-screen"><Brand/><span className="loading-line"/>Preparing your workspace</div>:error?<div className="empty"><h2>Couldn’t reach the local service</h2><p>{error}</p><Button onClick={load}>Retry</Button></div>:route.view==='invite'?<InvitationLanding/>:!state?<Welcome session={session} login={login} providerLogin={providerLogin} load={load} toast={toast}/>:state.kind==='provider'?<ProviderConsole/>:<Workspace key={`${state.workspace.id}:${state.provider?.accessId||state.user.id}`}/>}</Boundary><div className="toast-stack" aria-live="polite">{notices.map(n=><div className={`toast ${n.type}`} key={n.id}>{n.type==='error'?<CircleHelp size={18}/>:<Check size={18}/>}<span>{n.text}</span><button aria-label="Dismiss notification" onClick={()=>setNotices(x=>x.filter(y=>y.id!==n.id))}><X size={14}/></button></div>)}</div></Context.Provider>;
}
function Brand(){return <div className="brand"><span className="brand-mark"><Leaf size={24} strokeWidth={1.4}/></span><span>vayu<span className="brand-dot">.</span><small>DESIGN FOR LIVING</small></span></div>;}
function Welcome({session,login,providerLogin,load,toast}){
 const[register,setRegister]=useState(false),[plan,setPlan]=useState('Studio'),[busy,setBusy]=useState(false);
 return <div className="welcome"><header><Brand/><span className="local-label">LOCAL PREVIEW · SAMPLE DATA</span></header><main><div className="welcome-copy"><span className="eyebrow">A LITTLE MORE SPACE TO CREATE</span><h1>Your art.<br/>Your people.<br/><em>Beautifully connected.</em></h1><p>A considered workspace for your gallery. Curate collections, build relationships, and bring every detail together.</p><div className="row wrap"><Button icon={ArrowRight} onClick={()=>login('admin')}>Explore the workspace</Button><Button variant="secondary" onClick={()=>providerLogin('provider-owner')}>Open provider console</Button><Button variant="ghost" onClick={()=>setRegister(true)}>Try membership flow</Button></div><div className="welcome-note"><ShieldCheck size={17}/><span>Isolated local demo. No live accounts, payments, or deployments.</span></div></div><div className="welcome-art"><img src="/art/quiet.svg" alt="Abstract study in indigo and warm earth tones"/><div className="art-caption"><span>The quiet between</span><small>ANANYA SEN · SAMPLE ARTWORK</small></div><div className="floating-card"><span className="icon-surface"><Check size={18}/></span><div>A place for everything<small>And more room for what matters.</small></div></div></div></main><footer><span>EXPLORE ANOTHER PERSPECTIVE</span><div className="row wrap">{session?.profiles.map(p=><button key={p.id} className="profile-choice" onClick={()=>login(p.id)}>{p.name}<Badge>{p.role}</Badge></button>)}</div></footer>{register&&<Modal title="Create a sample workspace" onClose={()=>setRegister(false)}><form onSubmit={async e=>{e.preventDefault();setBusy(true);const values=Object.fromEntries(new FormData(e.target));try{await api('register',{...values,plan});await load();go('membership');}catch(e){toast(e.message,'error');}finally{setBusy(false);}}}><div className="form-grid"><p className="full muted">Explore the signup and plan flow locally. No password, card, or real payment is collected.</p><label>Your name<input name="name" required/></label><label>Email<input name="email" type="email" required/></label><label className="full">Workspace name<input name="workspace" required/></label><label className="full">Plan<select value={plan} onChange={e=>setPlan(e.target.value)}>{Object.keys(session.plans).map(p=><option key={p}>{p}</option>)}</select></label></div><footer className="modal-footer"><Button busy={busy}>Create sample workspace</Button></footer></form></Modal>}</div>;
}
function Workspace(){
 const{state,route,mutate,toast,login,logout,session,providerLogin,closeOrganization}=React.useContext(Context);
 const[menu,setMenu]=useState(false),[search,setSearch]=useState(''),[searchOpen,setSearchOpen]=useState(false),[notifications,setNotifications]=useState(false),[profile,setProfile]=useState(false),[create,setCreate]=useState(null);
 const isAdmin=state.user.role==='admin',guest=state.user.role==='guest';
 const available=nav.filter(([v])=>guest?['rooms','membership'].includes(v):!['audit','settings','trash'].includes(v)||isAdmin);
 useEffect(()=>{setMenu(false);setSearchOpen(false);document.getElementById('workspace-main')?.scrollTo(0,0);},[route.view,route.id]);
 useEffect(()=>{const h=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSearchOpen(true);document.getElementById('global-search')?.focus();}if(e.key==='Escape'){setSearchOpen(false);setMenu(false);setProfile(false);setNotifications(false);}};addEventListener('keydown',h);return()=>removeEventListener('keydown',h);},[]);
 const searchResults=search.trim()?['artworks','customers','catalogs','inquiries','rooms','conversations','invoices'].flatMap(type=>(state[type]||[]).filter(r=>`${r.title} ${r.artist||''} ${r.email||''} ${r.notes||''}`.toLowerCase().includes(search.toLowerCase())).map(r=>({...r,type}))).slice(0,12):[];
 const unread=state.notifications.filter(n=>!n.read).length;
 let view=route.view;
 const protectedAdmin=['audit','settings','trash'];
 const feature={artworks:'inventory'}[view]||view;
 const gated=!state.provider&&!['audit','overview','membership','settings','trash'].includes(view)&&!state.plans[state.workspace.plan].features.includes(feature);
 const inactive=!state.provider&&state.workspace.subscription!=='active'&&view!=='membership'&&view!=='settings';
 const content=()=>{
  if(!state.provider&&state.workspace.status==='suspended')return <Empty title="Organization access is paused" text="The provider has suspended this organization. Its records are preserved. Contact your provider to restore access."/>;
  if((protectedAdmin.includes(view)&&!isAdmin)||(guest&&!['rooms','membership'].includes(view)))return <Empty title="This area is restricted" text="Your workspace role does not grant access to this area." action={<Button onClick={()=>go(guest?'rooms':'overview')}>Back to workspace</Button>}/>;
  if(gated||inactive)return <div className="locked-feature"><LockKeyhole size={32}/><h1>{inactive?'Activate your workspace':'Room to grow'}</h1><p>{inactive?'Choose a simulated membership to explore your new workspace.':`${label(view)} is not included in your ${state.workspace.plan} plan. Existing records are preserved.`}</p><Button onClick={()=>go('membership')}>View membership</Button></div>;
  if(view==='overview')return <Overview/>;
  if(view==='artworks')return <Inventory/>;
  if(view==='collections')return <Collections/>;
  if(view==='catalogs')return route.id?<CatalogStudio/>:<Catalogs/>;
  if(['rooms','conversations'].includes(view))return <Collaboration type={view}/>;
  if(view==='reports')return <Reports/>;
  if(view==='membership')return <><Membership/><BillingEvents/></>;
  if(view==='settings')return <Administration/>;
  if(view==='audit')return <ActivityLog/>;
  if(view==='trash')return <Trash/>;
  if(['customers','inquiries','tasks','reservations','invoices','payments','deliveries'].includes(view))return <Records entity={view}/>;
  return <Empty title="Page not found" action={<Button onClick={()=>go('overview')}>Go home</Button>}/>;
 };
 return <div className={`app-shell ${state.provider?'provider-workspace':''}`}><aside id="workspace-navigation" className={`sidebar ${menu?'open':''}`}><div className="sidebar-brand"><Brand/><button className="icon-button mobile-only" aria-label="Close navigation" onClick={()=>setMenu(false)}><X/></button></div><div className="workspace-switch"><span className="workspace-monogram">VG</span><span>{state.workspace.name}<small>{state.workspace.plan} workspace</small></span><ChevronDown size={14}/></div><nav>{available.map(([v,title,Icon,section])=><React.Fragment key={v}>{section&&<div className="nav-section">{section}</div>}<button className={`nav-item ${view===v?'active':''}`} onClick={()=>go(v)}><Icon size={18} strokeWidth={1.6}/><span>{title}</span>{v==='tasks'&&state.tasks.filter(t=>t.status==='Open').length>0&&<span className="nav-count">{state.tasks.filter(t=>t.status==='Open').length}</span>}{view===v&&<span className="active-dot"/>}</button></React.Fragment>)}</nav><div className="sidebar-bottom"><div className="plan-note"><Sparkles size={17}/><div>A little room to grow<small>Explore your plan & usage</small></div><button aria-label="View membership" onClick={()=>go('membership')}><ArrowUpRight size={17}/></button></div><button className="sidebar-profile" onClick={()=>setProfile(!profile)}><Avatar user={state.user}/><span>{state.user.name}<small>{state.provider?'Provider':label(state.user.role)}</small></span><ChevronDown size={15}/></button></div></aside>{menu&&<div className="sidebar-scrim" onClick={()=>setMenu(false)}/>}
 <div className="workspace-body">{state.provider&&<div className="provider-access-banner"><ShieldCheck size={18}/><span><strong>Provider mode · {state.workspace.name}</strong><small>{state.provider.name} · Changes are recorded under your identity</small></span><button onClick={closeOrganization}>Provider console<ArrowUpRight size={15}/></button></div>}<header className="topbar"><div className="mobile-brand mobile-only"><Brand/></div><div className="breadcrumb"><span>Workspace</span><span>/</span><strong>{nav.find(n=>n[0]===view)?.[1]||'Overview'}</strong></div><div className="global-search"><Search size={17}/><input id="global-search" value={search} placeholder="Search your workspace…" aria-label="Search your workspace" onFocus={()=>setSearchOpen(true)} onChange={e=>{setSearch(e.target.value);setSearchOpen(true);}}/><kbd>⌘ K</kbd>{searchOpen&&<div className="search-results"><div className="popover-heading">{search?'SEARCH RESULTS':'FIND SOMETHING BEAUTIFUL'}<button className="icon-button" aria-label="Close search" onClick={()=>setSearchOpen(false)}><X size={15}/></button></div>{searchResults.map(r=><button key={r.id} onClick={()=>{go(r.type,r.id);setSearch('');setSearchOpen(false);}}><span>{r.title}<small>{label(r.type)}</small></span><ArrowUpRight size={15}/></button>)}{!searchResults.length&&<p>{search?'No matching records you can access.':'Search artworks, customers, catalogs, and more.'}</p>}</div>}</div><div className="topbar-actions"><span className="local-label"><span/>LOCAL PREVIEW</span><button className="icon-button notification-button" aria-label={`Notifications, ${unread} unread`} onClick={()=>setNotifications(!notifications)}><Bell size={19}/>{unread>0&&<i/>}</button><button className="avatar-button" aria-label="Account menu" onClick={()=>setProfile(!profile)}><Avatar user={state.user} size="small"/></button></div></header>
 <main id="workspace-main" className={`main-content ${['rooms','conversations'].includes(view)&&route.id?'chat-main':''}`} key={view}><div className="page-enter">{content()}</div><footer className="workspace-footer"><span>VAYU · DESIGN FOR LIVING</span><span>Made for the art of everyday.</span></footer></main>
 <nav className="bottom-nav">{(guest?[['rooms','Rooms',LockKeyhole],['membership','Plan',CreditCard]]:[['overview','Home',LayoutDashboard],['artworks','Inventory',Images],['inquiries','Sales',ClipboardList],['conversations','Messages',MessageCircle]]).map(([v,title,Icon])=><button key={v} className={view===v?'active':''} onClick={()=>go(v)}><Icon size={21}/><span>{title}</span></button>)}<button aria-controls="workspace-navigation" aria-expanded={menu} onClick={()=>setMenu(true)} className={menu?'active':''}><Menu size={21}/><span>More</span></button></nav></div>
 {notifications&&<Modal title="Notifications" onClose={()=>setNotifications(false)}><div className="notification-list">{state.notifications.length?state.notifications.slice().reverse().map(n=><button className={n.read?'read':''} key={n.id} onClick={async()=>{await mutate({action:'notification.read',entityId:n.id});go(n.route,n.targetId);setNotifications(false);}}><span className="notification-icon"><Bell size={18}/></span><span>{n.title}<small>{new Date(n.createdAt).toLocaleString()}</small></span>{!n.read&&<i/>}</button>):<Empty title="All caught up" text="Updates and invitations will appear here."/>}</div></Modal>}
 {profile&&<Modal title="Your local session" onClose={()=>setProfile(false)}><div className="profile-modal"><Avatar user={state.user}/><h3>{state.user.name}</h3><p>{state.user.email}</p><Badge>{state.provider?'Provider':state.user.role}</Badge>{!state.provider&&<Button variant="secondary" icon={ShieldCheck} onClick={async()=>{setProfile(false);await providerLogin('provider-owner');}}>Open local provider console</Button>}<div className="notice">Demo identity switching is enabled for local review only. It is not production authentication.</div><label>Explore another role<select value={state.user.id} onChange={async e=>{setProfile(false);await login(e.target.value);}}>{state.provider&&<option value={state.user.id}>Vayu Provider · provider</option>}{session.profiles.map(p=><option key={p.id} value={p.id}>{p.name} · {p.role}</option>)}</select></label><Button variant="secondary" icon={LogOut} onClick={async()=>{setProfile(false);await logout();}}>Sign out</Button></div></Modal>}
 {create&&<EntityForm entity={create} onClose={()=>setCreate(null)}/>}
 </div>;
}
