import React,{useEffect,useState} from 'react';
import { Plus, ArrowUpRight, ArrowRight, Images, BookOpen, ClipboardList, Wallet, MoreHorizontal, SlidersHorizontal, LayoutGrid, List, ChevronLeft, ChevronRight, Download, Upload, Save, Trash2, Link, Eye, Check, Clock3, FileText, Pencil, Search, GripVertical, X, Copy, Archive, Sparkles } from 'lucide-react';
import { useApp, Button, Badge, Avatar, ArtImage, Empty, PageHeading, SectionTitle, SearchField, Modal, Confirm, go, money, date, label, FilePicker, uploadFile, MultiSelect, api, readCSV, downloadJSON } from './lib.jsx';
import { EntityForm, NewRecordButton } from './forms.jsx';
import {ProductGallery} from './product-media.jsx';
export {Catalogs,CatalogStudio} from './catalog.jsx';

export function ArtworkCard({art,onClick,select,selected}){return <article className="art-card"><div className="art-card-image"><button onClick={onClick||(()=>go('artworks',art.id))} aria-label={`View ${art.title}`}><ArtImage art={art}/></button><Badge>{art.status}</Badge>{select&&<input className="card-checkbox" type="checkbox" aria-label={`Select ${art.title}`} checked={selected} onChange={select}/>}<button className="art-open" aria-label={`Open ${art.title}`} onClick={onClick||(()=>go('artworks',art.id))}><ArrowUpRight size={18}/></button></div><div className="art-card-info"><small>{art.artist||'ARTIST UNSPECIFIED'}</small><h3><button onClick={onClick||(()=>go('artworks',art.id))}>{art.title}</button></h3><div><span>{art.medium}</span><strong>{money(art.price)}</strong></div></div></article>;}
export function Overview(){
 const{state,mutate}=useApp();const open=state.tasks.filter(t=>t.status==='Open').sort((a,b)=>a.dueAt.localeCompare(b.dueAt));const unpaid=state.invoices.filter(i=>i.documentType!=='proforma'&&i.status==='Issued').reduce((n,i)=>n+i.total,0);
 const metrics=[['Available artworks',state.artworks.filter(a=>a.status==='Available').length,'Ready for their next home',Images,'artworks'],['Active inquiries',state.inquiries.filter(q=>!['Closed','Converted'].includes(q.status)).length,'Conversations worth nurturing',ClipboardList,'inquiries'],['Catalogs in your library',state.catalogs.length,'Thoughtfully put together',BookOpen,'catalogs'],['Outstanding value',money(unpaid),'Across unpaid invoices',Wallet,'invoices']];
 return <><PageHeading eyebrow={new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).toUpperCase()} title={`Good ${new Date().getHours()<12?'morning':new Date().getHours()<17?'afternoon':'evening'}, ${state.user.name.split(' ')[0]}.`} description="A little clarity. A little inspiration. Everything in its place."><NewRecordButton entity="artworks">Add artwork</NewRecordButton></PageHeading>
 <div className="overview-hero"><div><span className="eyebrow">CURATE SOMETHING MEANINGFUL</span><h2>Great art deserves<br/>a thoughtful introduction.</h2><p>Bring your artworks together in a catalog<br className="desktop-only"/> that feels as considered as the collection.</p><button onClick={()=>go('catalogs')}>Create your next catalog <ArrowUpRight size={18}/></button></div><div className="hero-art"><div className="hero-frame back"><img src="/art/earth.svg" alt="Earth-toned artwork"/></div><div className="hero-frame front"><img src="/art/geometry.svg" alt="Abstract geometric artwork"/></div></div><span className="hero-caption">THE ART OF BRINGING THINGS TOGETHER</span><span className="hero-index">01 / THE WORKSPACE</span></div>
 <div className="metrics">{metrics.map(([name,value,sub,Icon,view])=><button className="metric" key={name} onClick={()=>go(view)}><div><span>{name}</span><Icon size={18} strokeWidth={1.5}/></div><strong>{value}</strong><small>{sub}<ArrowUpRight size={13}/></small></button>)}</div>
 <div className="overview-middle"><section className="panel followup-panel"><SectionTitle title="A little attention, today" link="All follow-ups" onClick={()=>go('tasks')}/>{open.length?open.slice(0,3).map(t=><div className="task-row" key={t.id}><button className="task-check" aria-label={`Complete ${t.title}`} onClick={()=>mutate({action:'save',entity:'tasks',entityId:t.id,data:{...t,status:'Done'}},'Follow-up completed')}><Check size={13}/></button><button className="task-body" onClick={()=>go('tasks',t.id)}><strong>{t.title}</strong><span>{state.inquiries.find(q=>q.id===t.inquiryId)?.title||'Workspace follow-up'}</span></button><Badge>{t.dueAt<new Date().toISOString().slice(0,10)?'Overdue':t.dueAt===new Date().toISOString().slice(0,10)?'Today':date(t.dueAt)}</Badge><Avatar user={state.users.find(u=>u.id===t.assignee)} size="small"/></div>):<Empty title="A clear day ahead" text="No open follow-ups. Make space for something new."/>}</section><section className="studio-note"><span className="eyebrow">YOUR PRIVATE SPACES</span><div className="room-icon"><BookOpen size={23} strokeWidth={1.4}/></div><h3>Good things start<br/>{' '}with a conversation.</h3><p>Keep a project’s art, ideas, and people together in an invited-only room.</p><button className="text-button" onClick={()=>go('rooms')}>Open private rooms<ArrowUpRight size={16}/></button></section></div>
 <SectionTitle title="Fresh on the walls" link="View inventory" onClick={()=>go('artworks')}/><div className="art-grid overview-art-grid">{state.artworks.slice(0,4).map(a=><ArtworkCard key={a.id} art={a}/>)}</div>
 <div className="sample-note"><span/>Artwork and customer records shown here are synthetic samples. Your original system is untouched.</div></>;
}
export function Inventory(){
 const{state,route,mutate,toast}=useApp();const[search,setSearch]=useState(''),[filter,setFilter]=useState('All artworks'),[layout,setLayout]=useState('grid'),[selected,setSelected]=useState([]),[edit,setEdit]=useState(null),[confirm,setConfirm]=useState(null),[importOpen,setImportOpen]=useState(false),[bulkLocation,setBulkLocation]=useState(false);
 const art=state.artworks.find(a=>a.id===route.id);const rows=state.artworks.filter(a=>(filter==='All artworks'||a.status===filter)&&`${a.title} ${a.artist} ${a.medium}`.toLowerCase().includes(search.toLowerCase()));
 return <><PageHeading eyebrow="ART & CONTENT" title="The inventory" description="Every piece has a story. Keep yours beautifully organized."><Button variant="secondary" icon={Upload} onClick={()=>setImportOpen(true)}>Import CSV</Button><NewRecordButton entity="artworks">Add artwork</NewRecordButton></PageHeading><div className="inventory-summary"><span><strong>{state.artworks.length}</strong> artworks in your care</span><span className="dot-divider">·</span><span>{money(state.artworks.filter(a=>a.status!=='Sold').reduce((n,a)=>n+a.price,0))} inventory value</span></div><div className="list-toolbar"><div className="tabs">{['All artworks','Available','Reserved','Sold'].map(f=><button className={filter===f?'active':''} key={f} onClick={()=>setFilter(f)}>{f}<span>{state.artworks.filter(a=>f==='All artworks'||a.status===f).length}</span></button>)}</div><div className="row"><SearchField value={search} onChange={setSearch} placeholder="Search artworks…"/><div className="segmented"><button aria-label="Grid view" className={layout==='grid'?'active':''} onClick={()=>setLayout('grid')}><LayoutGrid size={17}/></button><button aria-label="Table view" className={layout==='table'?'active':''} onClick={()=>setLayout('table')}><List size={18}/></button></div></div></div>
 {selected.length>0&&<div className="selection-bar"><span>{selected.length} artworks selected</span><div className="row wrap"><Button variant="secondary" onClick={()=>{setEdit({entity:'collections',initial:{artworkIds:selected}});}}>Create collection</Button><Button onClick={()=>setEdit({entity:'catalogs',initial:{artworkIds:selected}})}>Create catalog</Button><Button variant="secondary" onClick={()=>setBulkLocation(true)}>Update location</Button>{state.user.role==='admin'&&<Button variant="secondary" icon={Download} onClick={()=>downloadJSON(state.artworks.filter(a=>selected.includes(a.id)),'vayu-selected-artworks.json')}>Export</Button>}<button className="icon-button" aria-label="Clear selection" onClick={()=>setSelected([])}><X size={16}/></button></div></div>}
 {bulkLocation&&<Modal title="Update selected artwork locations" onClose={()=>setBulkLocation(false)}><form onSubmit={async e=>{e.preventDefault();const location=new FormData(e.target).get('location');if(await mutate({action:'bulk.location',data:{ids:selected,location}},'Artwork locations updated'))setBulkLocation(false);}}><div className="modal-body"><p>Update the location of {selected.length} selected artworks. Availability and prices remain as recorded.</p><label>New location<input name="location" required maxLength={200}/></label></div><footer className="modal-footer"><Button>Update locations</Button></footer></form></Modal>}
 {!rows.length?<Empty title="No artworks found" text="Try a different search or add your first piece."/>:layout==='grid'?<div className="art-grid">{rows.map(a=><ArtworkCard art={a} key={a.id} selected={selected.includes(a.id)} select={()=>setSelected(s=>s.includes(a.id)?s.filter(x=>x!==a.id):[...s,a.id])}/>)}</div>:<div className="table-wrap"><table><thead><tr><th>Artwork</th><th>Artist</th><th>Medium</th><th>Status</th><th>Price</th></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><button className="table-art" onClick={()=>go('artworks',a.id)}><ArtImage art={a}/><strong>{a.title}</strong></button></td><td>{a.artist}</td><td>{a.medium}</td><td><Badge>{a.status}</Badge></td><td>{money(a.price)}</td></tr>)}</tbody></table></div>}
 {art&&<Modal wide title="Artwork details" onClose={()=>go('artworks')}><div className="art-detail"><div className="art-detail-image"><ProductGallery art={art}/></div><div className="art-detail-copy"><Badge>{art.status}</Badge><h2>{art.title}</h2><p className="artist-name">{art.artist}</p><h3>{money(art.price)}</h3><dl><div><dt>Medium</dt><dd>{art.medium||'—'}</dd></div><div><dt>Dimensions</dt><dd>{art.dimensions||'—'}</dd></div><div><dt>Year</dt><dd>{art.year||'—'}</dd></div><div><dt>Location</dt><dd>{art.location||'—'}</dd></div></dl><p>{art.description||'No description added.'}</p><div className="row wrap"><Button icon={Pencil} onClick={()=>setEdit({entity:'artworks',record:art})}>Edit artwork</Button>{art.status==='Available'&&<Button variant="secondary" onClick={()=>setEdit({entity:'reservations',initial:{artworkId:art.id,title:`${art.title} · reservation`}})}>Reserve</Button>}<Button variant="secondary" icon={BookOpen} onClick={()=>setEdit({entity:'catalogs',initial:{artworkIds:[art.id]}})}>Create catalog</Button><button className="icon-button danger-text" aria-label="Delete artwork" onClick={()=>setConfirm(art)}><Trash2 size={18}/></button></div></div></div></Modal>}
 {route.id&&!art&&<Modal title="Artwork unavailable" onClose={()=>go('artworks')}><Empty title="This artwork is no longer available" text="It may have been moved to trash or is outside your current access."/></Modal>}
 {edit&&<EntityForm {...edit} onClose={()=>setEdit(null)} onSaved={r=>{if(edit.entity==='catalogs')go('catalogs',r.id);}}/>}{confirm&&<Confirm title="Move to trash" text={`Move “${confirm.title}” to trash? Admins can restore it later.`} danger onClose={()=>setConfirm(null)} onConfirm={async()=>{if(await mutate({action:'trash',entity:'artworks',entityId:confirm.id},'Artwork moved to trash')){setConfirm(null);go('artworks');}}}/>}{importOpen&&<ImportModal onClose={()=>setImportOpen(false)}/>}</>;
}
export function ImportModal({onClose}){const{mutate,toast}=useApp();const[text,setText]=useState('title,artist,medium,dimensions,price,location\n'),[busy,setBusy]=useState(false);let rows=[],error='';try{rows=readCSV(text);}catch(e){error=e.message;}return <Modal wide title="Import artwork inventory" onClose={onClose}><div className="modal-body"><p>Upload or paste a CSV with <strong>title</strong> and <strong>price</strong>. Optional columns: artist, medium, dimensions, location, description. Maximum 200 artworks per import.</p><input type="file" aria-label="Choose inventory CSV" accept=".csv,text/csv" onChange={async e=>{if(e.target.files[0])setText(await e.target.files[0].text());}}/><textarea aria-label="CSV data" className="code-input" rows={8} value={text} onChange={e=>setText(e.target.value)}/><div className={error?'inline-error':'notice'}>{error||`${rows.length} valid rows ready. The entire import is checked before anything is saved.`}</div>{rows.length>0&&<div className="import-preview">{rows.slice(0,5).map((r,i)=><div key={i}><span>{r.title}</span><strong>{money(r.price)}</strong></div>)}</div>}</div><footer className="modal-footer"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button busy={busy} disabled={!!error||!rows.length} onClick={async()=>{setBusy(true);if(await mutate({action:'bulk.import',data:{rows}},`${rows.length} artworks imported`))onClose();setBusy(false);}}>Import {rows.length} artworks</Button></footer></Modal>;}
export function Collections(){const{state,route,mutate}=useApp();const[search,setSearch]=useState(''),[edit,setEdit]=useState(null),[remove,setRemove]=useState(null);const selected=state.collections.find(c=>c.id===route.id);return <><PageHeading eyebrow="ART & CONTENT" title="Considered collections" description="A shared feeling. A common thread. Art that belongs together."><NewRecordButton entity="collections">New collection</NewRecordButton></PageHeading><div className="list-toolbar"><span className="muted">{state.collections.length} collections</span><SearchField value={search} onChange={setSearch} placeholder="Find a collection…"/></div><div className="collection-grid">{state.collections.filter(c=>c.title.toLowerCase().includes(search.toLowerCase())).map(c=><article className="collection-card" key={c.id}><button className="collection-mosaic" onClick={()=>go('collections',c.id)}>{c.artworkIds.slice(0,3).map(aid=><ArtImage key={aid} art={state.artworks.find(a=>a.id===aid)}/>)}</button><div><span className="eyebrow">{c.artworkIds.length} ARTWORKS</span><h2><button onClick={()=>go('collections',c.id)}>{c.title}</button></h2><p>{c.description}</p><button className="text-button" onClick={()=>go('collections',c.id)}>Explore collection<ArrowUpRight size={16}/></button></div></article>)}</div>{!state.collections.length&&<Empty title="Find the common thread" text="Create your first collection of artworks."/>}{selected&&<Modal wide title={selected.title} onClose={()=>go('collections')}><div className="modal-body"><p>{selected.description}</p><div className="row wrap"><Button icon={Pencil} onClick={()=>setEdit({entity:'collections',record:selected})}>Edit collection</Button><Button variant="secondary" icon={BookOpen} onClick={()=>setEdit({entity:'catalogs',initial:{title:selected.title,description:selected.description,artworkIds:selected.artworkIds}})}>Create catalog</Button><Button variant="secondary" icon={Trash2} onClick={()=>setRemove(selected)}>Delete</Button></div><div className="art-grid compact">{selected.artworkIds.map(aid=>state.artworks.find(a=>a.id===aid)).filter(Boolean).map(a=><ArtworkCard key={a.id} art={a}/>)}</div></div></Modal>}{edit&&<EntityForm {...edit} onClose={()=>setEdit(null)} onSaved={r=>{if(edit.entity==='catalogs')go('catalogs',r.id);}}/>}{remove&&<Confirm title="Move to trash" text="The artworks themselves will remain in inventory." onClose={()=>setRemove(null)} onConfirm={async()=>{if(await mutate({action:'trash',entity:'collections',entityId:remove.id},'Collection moved to trash')){setRemove(null);go('collections');}}}/>}</>;}
