import React,{useState} from 'react';
import { Plus, ArrowUpRight, Pencil, Trash2, Check, CalendarDays, Clock3, MapPin, Mail, Phone, Receipt, CreditCard, Truck, Archive, ListTodo, Download, Users, ArrowRight, ExternalLink } from 'lucide-react';
import { useApp, Button, Badge, Avatar, ArtImage, Empty, PageHeading, SectionTitle, SearchField, Modal, Confirm, go, money, date, label, AttachmentList, downloadJSON } from './lib.jsx';
import { EntityForm, NewRecordButton, names } from './forms.jsx';
import {InvoiceDocument,PrintInvoiceButton} from './invoice-document.jsx';
import {isProforma,documentLabel} from '../shared/invoicing.mjs';
const descriptions={
 customers:['Your people','Good relationships begin with remembering the details.'],
 inquiries:['Conversations into possibilities','Every inquiry is the beginning of something.'],
 tasks:['A little attention goes a long way','The right follow-up, at the right time.'],
 reservations:['A place on hold','Keep a piece aside while a decision takes shape.'],
 invoices:['The finer details','Clear records for every considered purchase.'],
 payments:['Payments, in perspective','Track what’s received and what’s still on its way.'],
 deliveries:['From your walls to theirs','Packing, delivery, installation. Every step accounted for.']
};
function MobileRecordCards({entity,rows,state}){
 const today=new Date().toISOString().slice(0,10);
 return <div className="record-mobile-list">{rows.map(r=>{
  const invoice=state.invoices.find(i=>i.id===r.invoiceId);
  const customer=state.customers.find(c=>c.id===(r.customerId||invoice?.customerId));
  const member=state.users.find(u=>u.id===r.assignee);
  const inquiry=state.inquiries.find(q=>q.id===r.inquiryId);
  const isCustomer=entity==='customers',isTask=entity==='tasks',isMoney=['invoices','payments'].includes(entity);
  const subtitle=isCustomer?r.email||'Email not added':isTask?inquiry?.title||'Workspace follow-up':customer?.title||invoice?.title||inquiry?.title||'Workspace record';
  const overdue=isTask&&r.status==='Open'&&r.dueAt<today;
  const dateLabel=isTask?(overdue?'Overdue':'Due'):entity==='reservations'?'Expires':'Updated';
  const dateValue=isTask?r.dueAt:entity==='reservations'?r.expiresAt:r.updatedAt;
  const Icon=isTask?ListTodo:entity==='inquiries'?Users:entity==='deliveries'?Truck:entity==='reservations'?Archive:entity==='payments'?CreditCard:Receipt;
  return <button className="record-mobile-card" key={r.id} aria-label={`Open ${r.title}`} onClick={()=>go(entity,r.id)}>
   <span className="record-mobile-heading">
    {isCustomer?<Avatar user={{name:r.title}}/>:<span className={`record-symbol ${entity}`}><Icon size={18}/></span>}
    <span className="record-mobile-title"><strong>{r.title}</strong><small>{subtitle}</small></span>
    {!isCustomer&&<Badge>{r.status||'Open'}</Badge>}
   </span>
   <span className="record-mobile-details">
    {isCustomer?<><span><Phone size={14}/>{r.phone||'Phone not added'}</span><span><MapPin size={14}/>{[r.city,r.country].filter(Boolean).join(', ')||'Location not added'}</span></>:<>
     {(isTask||entity==='inquiries')&&<span><Avatar user={member} size="small"/>{member?.name||'Unassigned'}</span>}
     {entity==='inquiries'&&<span>{r.source||'Source not added'} · {r.artworkIds?.length||0} artworks</span>}
     {entity==='reservations'&&<span>{state.artworks.find(a=>a.id===r.artworkId)?.title||'Artwork unavailable'}</span>}
     {entity==='deliveries'&&<span><MapPin size={14}/>{r.address||'Delivery address not added'}</span>}
     {['payments','deliveries'].includes(entity)&&invoice&&customer&&<span>{invoice.title}</span>}
    </>}
   </span>
   <span className="record-mobile-footer">
    <span className={overdue?'danger-text':''}><CalendarDays size={14}/>{dateLabel} {date(dateValue)}</span>
    {isMoney&&<strong>{money(entity==='invoices'?r.total:r.amount)}</strong>}
    <ArrowUpRight size={17}/>
   </span>
  </button>;
 })}</div>;
}
export function Records({entity}){
 const{state,route,mutate}=useApp();const[search,setSearch]=useState(''),[status,setStatus]=useState('All'),[form,setForm]=useState(null),[remove,setRemove]=useState(null),[documentType,setDocumentType]=useState('all');
 const records=state[entity]||[],selected=records.find(r=>r.id===route.id);const statuses=[...new Set(records.map(r=>r.status).filter(Boolean))];const rows=records.filter(r=>(entity!=='invoices'||documentType==='all'||(r.documentType||'invoice')===documentType)&&(status==='All'||r.status===status)&&`${r.title} ${r.email||''} ${r.phone||''} ${state.customers.find(c=>c.id===r.customerId)?.title||''}`.toLowerCase().includes(search.toLowerCase()));
 const payable=records.filter(r=>!isProforma(r)&&['Issued','Paid'].includes(r.status));
 const stat=entity==='inquiries'?[['Active',records.filter(r=>!['Closed','Converted'].includes(r.status)).length],['New',records.filter(r=>r.status==='New').length],['Converted',records.filter(r=>r.status==='Converted').length]]:entity==='invoices'?[['Total invoiced',money(payable.reduce((n,x)=>n+x.total,0))],['Outstanding',money(payable.filter(x=>x.status==='Issued').reduce((n,x)=>n+x.total,0))],['Paid',payable.filter(x=>x.status==='Paid').length]]:entity==='tasks'?[['Open',records.filter(x=>x.status==='Open').length],['Overdue',records.filter(x=>x.status==='Open'&&x.dueAt<new Date().toISOString().slice(0,10)).length],['Completed',records.filter(x=>x.status==='Done').length]]:null;
 return <><PageHeading eyebrow={entity==='customers'||entity==='inquiries'||entity==='tasks'?'RELATIONSHIPS':'BUSINESS'} title={entity==='invoices'?'Invoices & PI':label(entity==='tasks'?'follow-ups':entity)} description={descriptions[entity][1]}>{entity==='invoices'&&<Button variant="secondary" icon={Plus} onClick={()=>setForm({entity:'invoices',initial:{documentType:'proforma'}})}>New PI</Button>}<NewRecordButton key={entity} entity={entity}>{`New ${names[entity]}`}</NewRecordButton></PageHeading>{stat&&<div className="mini-metrics">{stat.map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div>}{entity==='invoices'&&<nav className="invoice-kind-filter" aria-label="Document type">{[['all','All documents'],['invoice','Invoices'],['proforma','Proforma invoices (PI)']].map(([type,name])=><button key={type} aria-pressed={documentType===type} className={documentType===type?'active':''} onClick={()=>{setDocumentType(type);setStatus('All');}}>{name}</button>)}</nav>}{entity==='payments'&&<div className="notice"><CreditCard size={18}/><span>Local payment simulation. No payment links are sent and no money moves. Only an admin can simulate confirmation.</span></div>}
 <div className="list-toolbar"><div className="tabs"><button className={status==='All'?'active':''} onClick={()=>setStatus('All')}>All {entity==='tasks'?'follow-ups':entity}<span>{records.length}</span></button>{statuses.map(s=><button key={s} className={status===s?'active':''} onClick={()=>setStatus(s)}>{s}</button>)}</div><SearchField value={search} onChange={setSearch} placeholder={`Search ${entity}…`}/></div>
 {rows.length?<><MobileRecordCards entity={entity} rows={rows} state={state}/><div className="table-wrap records-table"><table><thead><tr><th>{entity==='customers'?'Customer':entity==='tasks'?'Follow-up':'Record'}</th><th>{entity==='customers'?'Contact':entity==='tasks'?'Assigned to':'Customer / linked record'}</th><th>{entity==='customers'?'Location':'Status'}</th><th>{['invoices','payments'].includes(entity)?'Amount':entity==='tasks'?'Due':entity==='reservations'?'Expires':'Updated'}</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{rows.map(r=>{const customer=state.customers.find(c=>c.id===r.customerId),invoice=state.invoices.find(i=>i.id===r.invoiceId),member=state.users.find(u=>u.id===r.assignee);return <tr key={r.id}><td><button className="record-title" onClick={()=>go(entity,r.id)}>{entity==='customers'?<Avatar user={{name:r.title}}/>:<span className={`record-symbol ${entity}`}>{entity==='tasks'?<ListTodo size={18}/>:entity==='inquiries'?<Users size={18}/>:entity==='deliveries'?<Truck size={18}/>:<Receipt size={18}/>}</span>}<span><strong>{r.title}</strong><small>{entity==='inquiries'?`${r.source} · ${r.artworkIds?.length||0} artworks`:entity==='customers'?r.email:entity==='tasks'?state.inquiries.find(q=>q.id===r.inquiryId)?.title:r.notes?.slice(0,55)||`Created ${date(r.createdAt)}`}</small></span></button></td><td>{entity==='customers'?r.phone||'—':entity==='tasks'?<span className="row"><Avatar user={member} size="small"/>{member?.name||'Unassigned'}</span>:customer?.title||invoice?.title||state.inquiries.find(q=>q.id===r.inquiryId)?.title||'—'}</td><td>{entity==='customers'?[r.city,r.country].filter(Boolean).join(', ')||'—':<Badge>{r.status||'Open'}</Badge>}</td><td>{entity==='invoices'?money(r.total):entity==='payments'?money(r.amount):entity==='tasks'?<span className={r.status==='Open'&&r.dueAt<new Date().toISOString().slice(0,10)?'danger-text':''}>{date(r.dueAt)}</span>:entity==='reservations'?date(r.expiresAt):date(r.updatedAt)}</td><td><button className="icon-button" aria-label={`Open ${r.title}`} onClick={()=>go(entity,r.id)}><ArrowUpRight size={18}/></button></td></tr>;})}</tbody></table></div></>:<Empty title={`No ${entity==='tasks'?'follow-ups':entity} here yet`} text="Add a record or adjust your search to get started."/>}
 {selected&&<RecordDetail key={selected.id} entity={entity} record={selected} onClose={()=>go(entity)} onEdit={()=>setForm({entity,record:selected})} onDelete={()=>setRemove(selected)} onCreate={(entity,initial)=>setForm({entity,initial})}/>}
 {route.id&&!selected&&<Modal title="Record unavailable" onClose={()=>go(entity)}><Empty title="This record is unavailable" text="It may have been deleted or is outside your current plan."/></Modal>}
 {form&&<EntityForm {...form} onClose={()=>setForm(null)} onSaved={r=>{if(form.entity!==entity)go(form.entity,r.id);}}/>}{remove&&<Confirm title="Move to trash" text={`Move “${remove.title}” to trash? Linked financial records may require this record to be retained.`} danger onClose={()=>setRemove(null)} onConfirm={async()=>{if(await mutate({action:'trash',entity,entityId:remove.id},'Record moved to trash')){setRemove(null);go(entity);}}}/>}</>;
}
export function RecordDetail({entity,record:r,onClose,onEdit,onDelete,onCreate:onCreateRecord}){
 const onCreate=(target,initial)=>onCreateRecord(target,target==='catalogs'&&entity==='inquiries'?{...initial,customerId:r.customerId,inquiryId:r.id}:initial);
 const{state,mutate}=useApp();const customer=state.customers.find(c=>c.id===r.customerId);const arts=(r.artworkIds||[r.artworkId]).map(id=>state.artworks.find(a=>a.id===id)).filter(Boolean);const address=['address','city','region','postal','country'].map(k=>r[k]).filter(Boolean).join(', ');
 const [confirm,setConfirm]=useState(null);
 const follow=()=>onCreate('tasks',{title:`Follow up: ${r.title}`,inquiryId:r.id,assignee:r.assignee||state.user.id});
 return <Modal wide title={r.title} onClose={onClose}><div className="record-detail"><div className="record-detail-header"><div>{entity==='invoices'&&<Badge>{documentLabel(r)}</Badge>}{r.status&&<Badge>{r.status}</Badge>}<span className="muted">Created {date(r.createdAt)}</span></div><div className="row wrap">{!['payments','reservations'].includes(entity)&&(entity!=='invoices'||r.status==='Draft')&&<Button variant="secondary" icon={Pencil} onClick={onEdit}>Edit</Button>}{(entity!=='invoices'||r.status==='Draft'&&!r.sourceProformaId)&&<button className="icon-button danger-text" aria-label="Delete record" onClick={onDelete}><Trash2 size={18}/></button>}</div></div>
 {entity==='customers'&&<><div className="customer-hero"><Avatar user={{name:r.title}}/><div><h2>{r.title}</h2><p>{r.notes||'A relationship worth keeping.'}</p></div></div><div className="contact-grid"><div><Mail size={17}/>{r.email||'No email'}</div><div><Phone size={17}/>{r.phone||'No phone'}</div><div className="full"><MapPin size={17}/>{address||'No address added'}</div></div><Button icon={Plus} onClick={()=>onCreate('inquiries',{customerId:r.id,title:`Inquiry · ${r.title}`,address:r.address,city:r.city,region:r.region,postal:r.postal,country:r.country})}>New inquiry</Button><SectionTitle title="Relationship history"/>{['inquiries','reservations','invoices'].map(type=><div key={type} className="linked-section"><h4>{label(type)}</h4>{state[type].filter(x=>x.customerId===r.id).map(x=><button className="linked-row" key={x.id} onClick={()=>go(type,x.id)}><span>{x.title}</span><Badge>{x.status}</Badge><ArrowUpRight size={15}/></button>)}{!state[type].some(x=>x.customerId===r.id)&&<p className="muted">No {type} yet.</p>}</div>)}</>}
 {entity==='inquiries'&&<><div className="detail-stats"><div><span>Customer</span><button className="text-button" onClick={()=>go('customers',customer?.id)}>{customer?.title||'Customer unavailable'}<ArrowUpRight size={14}/></button></div><div><span>Assigned to</span><strong>{state.users.find(u=>u.id===r.assignee)?.name||'Unassigned'}</strong></div><div><span>Source</span><strong>{r.source}</strong></div></div><div className="address-box"><MapPin size={19}/><div><strong>Customer address</strong><p>{address||'No address added. Edit this inquiry to add one.'}</p></div></div><p>{r.notes||'No notes yet.'}</p><div className="row wrap"><Button icon={CalendarDays} onClick={follow}>Add follow-up</Button><Button variant="secondary" icon={Archive} onClick={()=>onCreate('reservations',{title:`${r.title} · reservation`,customerId:r.customerId,inquiryId:r.id,artworkId:arts.find(a=>a.status==='Available')?.id||''})}>Reserve artwork</Button><Button variant="secondary" icon={Receipt} onClick={()=>onCreate('invoices',{customerId:r.customerId,inquiryId:r.id,artworkIds:r.artworkIds.filter(id=>state.artworks.find(a=>a.id===id)?.status!=='Sold')})}>Create invoice</Button><Button variant="secondary" onClick={()=>onCreate('catalogs',{title:`Selection for ${customer?.title||'customer'}`,artworkIds:r.artworkIds})}>Create catalog</Button></div><SectionTitle title="Interested artworks"/><LinkedArt arts={arts}/><SectionTitle title="Photos & attachments"/><AttachmentList ids={r.attachments}/>{!r.attachments.length&&<p className="muted">No attachments yet. Use Edit to take a photo or upload an image.</p>}<SectionTitle title="Follow-ups"/>{state.tasks.filter(t=>t.inquiryId===r.id).map(t=><button key={t.id} className="linked-row" onClick={()=>go('tasks',t.id)}><span>{t.title}</span><Badge>{t.status}</Badge><span>{date(t.dueAt)}</span></button>)}</>}
 {entity==='tasks'&&<><div className="detail-stats"><div><span>Due date</span><strong>{date(r.dueAt)}</strong></div><div><span>Assigned to</span><strong>{state.users.find(u=>u.id===r.assignee)?.name}</strong></div></div>{r.inquiryId&&<button className="linked-row" onClick={()=>go('inquiries',r.inquiryId)}>Open linked inquiry<ArrowUpRight size={16}/></button>}<Button icon={Check} onClick={()=>mutate({action:'save',entity,entityId:r.id,data:{...r,status:r.status==='Done'?'Open':'Done'}},r.status==='Done'?'Follow-up reopened':'Follow-up completed')}>{r.status==='Done'?'Reopen follow-up':'Mark complete'}</Button></>}
 {entity==='reservations'&&<><div className="detail-stats"><div><span>Customer</span><strong>{customer?.title}</strong></div><div><span>Expires</span><strong>{new Date(r.expiresAt).toLocaleString()}</strong></div></div><LinkedArt arts={arts}/><p className="muted">Expiry is checked by the local service. An expired reservation returns the artwork to available.</p>{r.status==='Active'&&<div className="row"><Button icon={Receipt} onClick={()=>onCreate('invoices',{customerId:r.customerId,inquiryId:r.inquiryId,artworkIds:[r.artworkId]})}>Create invoice</Button><Button variant="secondary" onClick={()=>setConfirm({title:'Cancel reservation',text:'Release this artwork back to inventory?',action:'reservation.cancel'})}>Release reservation</Button></div>}</>}
 {entity==='invoices'&&<><InvoiceDocument record={r}/><div className="row wrap">{r.status==='Draft'&&<Button onClick={()=>setConfirm({title:`Issue ${isProforma(r)?'proforma invoice':'invoice'}`,text:'The billing details and artwork prices will be locked. Check both addresses and GSTINs before issuing.',action:'invoice.issue'})}>Issue {isProforma(r)?'PI':'invoice'}</Button>}{isProforma(r)&&r.status==='Issued'&&<Button onClick={async()=>{const invoice=await mutate({action:'invoice.convert',entityId:r.id},'PI converted to a draft invoice');if(invoice)go('invoices',invoice.id);}}>Convert to invoice</Button>}{r.convertedInvoiceId&&<Button variant="secondary" onClick={()=>go('invoices',r.convertedInvoiceId)}>Open linked invoice<ArrowUpRight size={15}/></Button>}{r.sourceProformaId&&<Button variant="secondary" onClick={()=>go('invoices',r.sourceProformaId)}>View source PI</Button>}{!isProforma(r)&&r.status==='Issued'&&<Button variant="secondary" icon={CreditCard} onClick={()=>onCreate('payments',{title:`Payment · ${r.title}`,invoiceId:r.id})}>Create payment request</Button>}{!isProforma(r)&&r.status==='Paid'&&<Button icon={Truck} onClick={()=>onCreate('deliveries',{title:`Delivery · ${r.title}`,invoiceId:r.id,address:r.customerAddress||''})}>Arrange delivery</Button>}<PrintInvoiceButton record={r}/><Button variant="secondary" icon={Download} onClick={()=>downloadJSON(r,`${r.title}.json`)}>Export record</Button></div><p className="muted">{isProforma(r)?'A PI is excluded from invoice totals and payment requests. Convert it when the customer is ready.':'Issuing saves the document locally. It does not send an email.'}</p></>}
 {entity==='payments'&&<><div className="payment-total"><small>PAYMENT AMOUNT</small><h2>{money(r.amount)}</h2><Badge>{r.status}</Badge></div><div className="notice">Local simulation only. No payment provider is connected.</div><button className="linked-row" onClick={()=>go('invoices',r.invoiceId)}><span>{state.invoices.find(i=>i.id===r.invoiceId)?.title||'Linked invoice'}</span><ArrowUpRight size={16}/></button><p>{r.method}</p>{r.verifiedAt&&<p>Recorded {new Date(r.verifiedAt).toLocaleString()}</p>}{r.status!=='Paid'&&state.user.role==='admin'&&<Button icon={Check} onClick={()=>setConfirm({title:'Simulate paid',text:'This marks the invoice paid and its artworks sold in sample data. No money moves.',action:'payment.simulate'})}>Simulate payment confirmation</Button>}</>}
 {entity==='deliveries'&&<><div className="delivery-timeline">{['Packing','Dispatched','Delivered','Installed'].map((v,i)=><div key={v} className={i<=['Packing','Dispatched','Delivered','Installed'].indexOf(r.status)?'complete':''}><span>{i<['Packing','Dispatched','Delivered','Installed'].indexOf(r.status)?<Check size={15}/>:i+1}</span><strong>{v}</strong></div>)}</div><div className="address-box"><MapPin size={20}/><div><strong>Delivery address</strong><p>{r.address||'No address added'}</p></div></div><p><strong>Tracking reference:</strong> {r.tracking||'Not added'}</p><p>{r.notes}</p><SectionTitle title="Proof of delivery"/><AttachmentList ids={r.attachments}/><Button icon={Pencil} onClick={onEdit}>Update delivery</Button></>}
 {entity==='customers'&&<CustomerCatalogHistory customerId={r.id}/>}</div>{confirm&&<Confirm title={confirm.title} text={confirm.text} onClose={()=>setConfirm(null)} onConfirm={async()=>{if(await mutate({action:confirm.action,entityId:r.id},'Record updated'))setConfirm(null);}}/>}</Modal>;
}
function CustomerCatalogHistory({customerId}){const{state}=useApp();const rows=state.catalogs.filter(c=>c.customerId===customerId);return <div className="linked-section"><h4>Catalogs prepared for this customer</h4>{rows.map(c=><button className="linked-row" key={c.id} onClick={()=>go('catalogs',c.id)}><span>{c.title}</span><Badge>{state.shares.some(s=>s.catalogId===c.id&&!s.revokedAt&&Date.parse(s.expiresAt)>Date.now())?'Active share link':c.versions.length?'Saved':'Draft'}</Badge><ArrowUpRight size={15}/></button>)}{!rows.length&&<p className="muted">No linked catalogs yet. Create one from this customer’s inquiry.</p>}</div>;}
function LinkedArt({arts}){return <div className="linked-art-grid">{arts.map(a=><button key={a.id} onClick={()=>go('artworks',a.id)}><ArtImage art={a}/><span><strong>{a.title}</strong><small>{a.artist}</small><Badge>{a.status}</Badge></span><ArrowUpRight size={16}/></button>)}</div>;}
export function Reports(){
 const{state}=useApp();const[period,setPeriod]=useState('All time');const cutoff=period==='30 days'?Date.now()-30*86400000:period==='90 days'?Date.now()-90*86400000:0;
 const invoices=state.invoices.filter(x=>!isProforma(x)&&Date.parse(x.createdAt)>=cutoff),inquiries=state.inquiries.filter(x=>Date.parse(x.createdAt)>=cutoff);const revenue=invoices.filter(x=>x.status==='Paid').reduce((n,x)=>n+x.total,0),outstanding=invoices.filter(x=>x.status==='Issued').reduce((n,x)=>n+x.total,0),converted=inquiries.filter(x=>x.status==='Converted').length;
 const months=Array.from({length:6},(_,i)=>{const d=new Date();d.setMonth(d.getMonth()-5+i,1);const key=d.toISOString().slice(0,7);return {label:d.toLocaleDateString('en',{month:'short'}),value:state.payments.filter(p=>p.status==='Paid'&&(p.verifiedAt||'').slice(0,7)===key&&Date.parse(p.verifiedAt)>=cutoff).reduce((n,p)=>n+p.amount,0)};});const max=Math.max(1,...months.map(m=>m.value));
 const summary={period,revenue,outstanding,inquiryCount:inquiries.length,converted,inventoryValue:state.artworks.filter(a=>a.status!=='Sold').reduce((n,a)=>n+a.price,0)};
 return <><PageHeading eyebrow="BUSINESS INTELLIGENCE" title="A clearer perspective" description="A view of your gallery, grounded in the records you keep."><select aria-label="Report period" value={period} onChange={e=>setPeriod(e.target.value)}>{['All time','30 days','90 days'].map(p=><option key={p}>{p}</option>)}</select>{state.user.role==='admin'&&<Button variant="secondary" icon={Download} onClick={()=>downloadJSON(summary,'vayu-report.json')}>Export summary</Button>}</PageHeading><div className="metrics report-metrics">{[['Paid invoice value',money(revenue)],['Outstanding',money(outstanding)],['Inquiry conversion',`${inquiries.length?Math.round(converted/inquiries.length*100):0}%`],['Inventory value',money(summary.inventoryValue)]].map(([k,v])=><div className="metric" key={k}><span>{k}</span><strong>{v}</strong><small>{k==='Inventory value'?'Current unsold inventory':period}</small></div>)}</div><div className="report-grid"><section className="panel"><SectionTitle title="Payments received"/><p className="muted">Recorded sample payments over the last six months</p><div className="bar-chart" role="img" aria-label={months.map(m=>`${m.label}: ${money(m.value)}`).join(', ')}>{months.map(m=><div key={m.label}><strong>{m.value?money(m.value):'—'}</strong><span style={{height:`${Math.max(2,m.value/max*180)}px`}}/><small>{m.label}</small></div>)}</div></section><section className="panel"><SectionTitle title="Inquiry pipeline"/>{['New','Contacted','Interested','Converted','Closed'].map(status=>{const count=inquiries.filter(q=>q.status===status).length;return <div className="pipeline-row" key={status}><div><Badge>{status}</Badge><strong>{count}</strong></div><span><i style={{width:`${inquiries.length?count/inquiries.length*100:0}%`}}/></span></div>;})}</section></div><section className="panel"><SectionTitle title="Team workload"/><div className="workload-grid">{state.users.filter(u=>u.role!=='guest'&&!u.disabled).map(u=><div key={u.id}><Avatar user={u}/><div><strong>{u.name}</strong><span>{state.tasks.filter(t=>t.assignee===u.id&&t.status==='Open').length} open follow-ups · {state.inquiries.filter(q=>q.assignee===u.id&&!['Closed','Converted'].includes(q.status)).length} active inquiries</span></div></div>)}</div></section></>;
}
