import React,{useEffect,useRef,useState} from 'react';
import {Plus,FileText,Download,ChevronRight,Trash2,Eye,Link,Copy,ArrowUpRight,Check,SlidersHorizontal,WandSparkles} from 'lucide-react';
import {useApp,Button,Badge,SearchField,Empty,Modal,Confirm,FilePicker,go,date,api} from './lib.jsx';
import {EntityForm} from './forms.jsx';
import {normalizeDesign,templates} from '../shared/catalog-design.mjs';
import {renderCatalogPage,makePDF} from './catalog-renderer.js';
import {CatalogGenerator} from './catalog-studio.jsx';

function CatalogNav({active,onChange,counts={}}){return <nav className="catalog-sections" aria-label="Catalog sections">{[['library','Library'],['designer','Designer']].map(([key,name])=><button key={key} aria-current={active===key?'page':undefined} className={active===key?'active':''} onClick={()=>onChange(key)}>{name}{counts[key]!==undefined&&<span className="catalog-tab-count">{counts[key]}</span>}</button>)}</nav>;}
function TemplatePicker({value,onChange}){return <div className="template-picker">{templates.map(t=><button type="button" title={t.description} aria-pressed={value===t.id} className={value===t.id?'active':''} key={t.id} onClick={()=>onChange(t.id)}><span className={`template-mini template-${t.id}`}><i/><b/><em/></span><span>{t.name}</span>{value===t.id&&<Check size={13}/>}</button>)}</div>;}
export function Catalogs(){return <CatalogHome/>;}
function CatalogHome(){
 const{state,mutate}=useApp(),[section,setSection]=useState('library'),[search,setSearch]=useState(''),[filter,setFilter]=useState('All'),[create,setCreate]=useState(false),[open,setOpen]=useState(null);
 const opened=state.catalogs.find(c=>c.id===open),library=state.catalogs.filter(c=>c.versions.length),all=section==='library'?library:state.catalogs,rows=all.filter(c=>c.title.toLowerCase().includes(search.toLowerCase())&&(section==='designer'||filter==='All'||c.versions.some(v=>v.source===filter))).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt));
 const upload=async f=>{const c=await mutate({action:'save',entity:'catalogs',data:{title:f.name.replace(/\.pdf$/i,''),theme:'Ivory',artworkIds:[]}});if(c&&await mutate({action:'catalog.version',entityId:c.id,data:{fileId:f.id}},'Uploaded catalog saved to Library')){setSection('library');setOpen(c.id);}};
 return <div className="catalog-home"><header className="catalog-home-heading"><div><h1>Catalog</h1><p>Keep your PDFs together. Create your next collection.</p></div><div className="row"><FilePicker accept="application/pdf" label="Upload PDF" onUpload={upload}/><Button icon={Plus} onClick={()=>setCreate(true)}>Create catalog</Button></div></header>
 <div className="catalog-home-toolbar"><CatalogNav active={section} onChange={setSection} counts={{library:library.length,designer:state.catalogs.length}}/><div className="catalog-find"><SearchField value={search} onChange={setSearch} placeholder="Search catalogs…"/>{section==='library'&&<select aria-label="Catalog type" value={filter} onChange={e=>setFilter(e.target.value)}><option value="All">All types</option><option value="Generated">Generated</option><option value="Uploaded">Uploaded</option></select>}</div></div>
 <div className="catalog-list-caption"><span>{section==='library'?'Saved PDFs':'Editable catalogs'}</span><small>{rows.length} {rows.length===1?'catalog':'catalogs'}</small></div>
 <div className="catalog-records">{rows.map(c=>{const d=normalizeDesign(c.design,c.theme),last=c.versions.at(-1),image=d.coverImage||state.artworks.find(a=>a.id===c.artworkIds[0])?.bannerImage||state.artworks.find(a=>a.id===c.artworkIds[0])?.image;return <article className="catalog-record" key={c.id}><button className="catalog-record-thumbnail" aria-label={`View ${c.title}`} style={{background:d.background}} onClick={()=>section==='library'?setOpen(c.id):go('catalogs',c.id)}>{image?<img src={image} alt=""/>:<FileText size={26} strokeWidth={1.3}/>}</button><div className="catalog-record-copy"><h2><button onClick={()=>section==='library'?setOpen(c.id):go('catalogs',c.id)}>{c.title}</button></h2><p>{section==='library'?`${c.versions.length} saved ${c.versions.length===1?'version':'versions'}`:`${c.artworkIds.length} ${c.artworkIds.length===1?'product':'products'}`}<span>·</span>{date(c.updatedAt)}</p></div><Badge>{last?last.source:'Draft'}</Badge><div className="catalog-record-actions">{section==='library'&&last?<a className="button secondary" href={`/api/files/${last.fileId}`} target="_blank" rel="noreferrer" aria-label={`Open PDF: ${c.title}`}>Open PDF<ArrowUpRight size={15}/></a>:<Button variant="secondary" onClick={()=>go('catalogs',c.id)} aria-label={`Edit design: ${c.title}`}>Edit design<ArrowUpRight size={15}/></Button>}<button className="icon-button" aria-label={`Manage ${c.title}`} title="Versions, sharing and deletion" onClick={()=>setOpen(c.id)}><SlidersHorizontal size={17}/></button></div></article>;})}</div>
 {!rows.length&&<Empty title={search||filter!=='All'?'No matching catalogs':section==='library'?'Your library starts here':'Create your first catalog'} text={search||filter!=='All'?'Try another name or clear the filters.':section==='library'?'Upload a PDF or create a catalog to save it here.':'Choose your products, customize the design, then save a PDF.'} action={search||filter!=='All'?<Button variant="secondary" onClick={()=>{setSearch('');setFilter('All');}}>Clear filters</Button>:<Button icon={Plus} onClick={()=>setCreate(true)}>Create catalog</Button>}/>}
 {create&&<NewCatalog onClose={()=>setCreate(false)}/>} {opened&&<LibraryDetail catalog={opened} onClose={()=>setOpen(null)}/>}</div>;
}
function NewCatalog({onClose}){
 const{state,mutate,toast,refresh}=useApp(),recovered=state.drafts.find(d=>d.entity==='catalogs'&&!d.entityId)?.data||{},initial=useRef(recovered);
 const[name,setName]=useState(recovered.title||''),[template,setTemplate]=useState(recovered.design?.template||'editorial'),[customer,setCustomer]=useState(recovered.customerId||''),[inquiry,setInquiry]=useState(recovered.inquiryId||''),[busy,setBusy]=useState(false),[draftStatus,setDraftStatus]=useState(recovered.title?'Draft recovered':'');
 const timer=useRef(),saving=useRef(false),data={...initial.current,title:name,theme:initial.current.theme||'Ivory',artworkIds:initial.current.artworkIds||[],customerId:customer,inquiryId:inquiry,design:normalizeDesign({...initial.current.design,template})};
 const changed=name!==(initial.current.title||'')||template!==(initial.current.design?.template||'editorial')||customer!==(initial.current.customerId||'')||inquiry!==(initial.current.inquiryId||'');
 useEffect(()=>{if(!changed||saving.current)return;setDraftStatus('Saving draft…');timer.current=setTimeout(()=>api('action',{action:'draft.save',entity:'catalogs',data}).then(()=>setDraftStatus('Draft saved')).catch(()=>setDraftStatus('Draft not saved')),650);return()=>clearTimeout(timer.current);},[name,template,customer,inquiry]);
 const close=async()=>{clearTimeout(timer.current);if(changed&&!saving.current){try{await api('action',{action:'draft.save',entity:'catalogs',data});await refresh();}catch(e){toast(e.message,'error');return;}}onClose();};
 return <Modal title="Create catalog" onClose={close}><form onSubmit={async e=>{e.preventDefault();clearTimeout(timer.current);saving.current=true;setBusy(true);const c=await mutate({action:'save',entity:'catalogs',data},'Catalog created');setBusy(false);if(c){await api('action',{action:'draft.delete',entity:'catalogs'}).catch(()=>{});await refresh();onClose();go('catalogs',c.id);}else saving.current=false;}}><div className="modal-body catalog-new"><label>Catalog name<input value={name} required maxLength={200} placeholder="e.g. Summer collection" onChange={e=>setName(e.target.value)}/></label><p>You'll choose products and customize the pages next.</p><details><summary>Choose a cover template</summary><TemplatePicker value={template} onChange={setTemplate}/></details><details><summary>Link to a customer or inquiry</summary><label>Customer<select value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">No customer</option>{state.customers.map(c=><option value={c.id} key={c.id}>{c.title}</option>)}</select></label><label>Inquiry<select value={inquiry} onChange={e=>setInquiry(e.target.value)}><option value="">No inquiry</option>{state.inquiries.map(q=><option key={q.id} value={q.id}>{q.title}</option>)}</select></label></details></div><footer className="modal-footer"><span className="draft-status">{draftStatus}</span><Button type="button" variant="secondary" onClick={close}>Cancel</Button><Button busy={busy}>Choose products<ChevronRight size={16}/></Button></footer></form></Modal>;
}
function SavedVersions({catalog}){const{mutate}=useApp();return <section className="saved-versions panel"><div className="row between wrap"><div><h2>Saved PDFs</h2><p className="muted">Each version keeps the design and product details from when it was saved.</p></div><FilePicker accept="application/pdf" label="Upload catalog version" onUpload={f=>mutate({action:'catalog.version',entityId:catalog.id,data:{fileId:f.id}},'Version saved to Library')}/></div>{catalog.versions.length?<div className="version-list">{catalog.versions.slice().reverse().map(v=><div key={v.id}><span className="file-icon"><FileText size={22}/></span><div><strong>Version {v.number} · {v.source}</strong><small>{date(v.createdAt)}</small></div><a className="button secondary" href={`/api/files/${v.fileId}`} target="_blank" rel="noreferrer"><Eye size={16}/>Preview PDF</a><a className="icon-button" aria-label={`Download version ${v.number}`} href={`/api/files/${v.fileId}?download`}><Download size={18}/></a></div>)}</div>:<Empty title="No saved PDF yet" text="Generate the design or upload a PDF to store it in Library."/>}</section>;}
function LibraryDetail({catalog,onClose}){const{mutate}=useApp(),[share,setShare]=useState(false),[remove,setRemove]=useState(false);return <Modal wide title={catalog.title} onClose={onClose}><div className="modal-body"><div className="row wrap"><Button onClick={()=>{onClose();go('catalogs',catalog.id);}} icon={WandSparkles}>Open designer</Button><Button variant="secondary" icon={Link} disabled={!catalog.versions.length} onClick={()=>setShare(true)}>Share catalog</Button><Button variant="ghost danger-text" icon={Trash2} onClick={()=>setRemove(true)}>Delete catalog</Button></div><SavedVersions catalog={catalog}/></div>{share&&<ShareModal catalog={catalog} onClose={()=>setShare(false)}/>} {remove&&<Confirm danger title="Move catalog to trash" text="Saved PDFs will leave Library and share links will be revoked. An admin can restore the catalog." onClose={()=>setRemove(false)} onConfirm={async()=>{if(await mutate({action:'trash',entity:'catalogs',entityId:catalog.id},'Catalog moved to trash'))onClose();}}/>}</Modal>;}
export function CatalogStudio(){const{state,route}=useApp(),catalog=state.catalogs.find(c=>c.id===route.id);return catalog?<Designer key={catalog.id} catalog={catalog}/>:<Empty title="Catalog unavailable" text="It may have been removed or is outside your current access." action={<Button onClick={()=>go('catalogs')}>Back to Catalog</Button>}/>;}
export function Designer({catalog}){return <CatalogGenerator catalog={catalog} renderVersions={(c,close)=><LibraryDetail catalog={c} onClose={close}/>} renderArtwork={(art,close)=><EntityForm entity="artworks" record={art} onClose={close}/>}/>;}
function ShareModal({catalog,onClose}){const{state,mutate,toast}=useApp(),[days,setDays]=useState(7),[version,setVersion]=useState(catalog.versions.at(-1)?.id),shares=state.shares.filter(s=>s.catalogId===catalog.id);return <Modal title="Share a saved catalog" onClose={onClose}><div className="modal-body"><p>Anyone with the link can access the PDF until it expires or is revoked. Local links work only on this computer.</p><div className="form-grid"><label>Saved version<select value={version} onChange={e=>setVersion(e.target.value)}>{catalog.versions.map(v=><option key={v.id} value={v.id}>Version {v.number} · {v.source}</option>)}</select></label><label>Expires after<select value={days} onChange={e=>setDays(+e.target.value)}>{[1,7,30,90].map(d=><option key={d} value={d}>{d} days</option>)}</select></label></div><Button icon={Link} onClick={()=>mutate({action:'share.create',entityId:catalog.id,data:{days,versionId:version}},'Expiring link created')}>Create link</Button><div className="share-list">{shares.map(s=><div key={s.id}><div className="row between"><Badge>{s.revokedAt?'Revoked':Date.parse(s.expiresAt)<Date.now()?'Expired':'Active'}</Badge><small>Expires {date(s.expiresAt)}</small></div><input aria-label="Catalog share link" readOnly value={`${location.origin}/api/shared/${s.token}`}/><div className="row"><Button variant="secondary" icon={Copy} onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/api/shared/${s.token}`);toast('Local catalog link copied');}catch{toast('Copy the link shown above.','error');}}}>Copy link</Button>{!s.revokedAt&&<Button variant="ghost danger-text" onClick={()=>mutate({action:'share.revoke',entityId:s.id},'Link revoked')}>Revoke access</Button>}</div></div>)}</div></div></Modal>;}
