import React,{useEffect,useRef,useState} from 'react';
import { Save, Plus } from 'lucide-react';
import {ProductMedia} from './product-media.jsx';
import {InvoicePartyFields} from './invoice-document.jsx';
import {formatPartyAddress} from '../shared/invoicing.mjs';
import { useApp, Modal, Button, MultiSelect, FilePicker, AttachmentList, label, api } from './lib.jsx';

const schema={
  artworks:[['title','Artwork title','required'],['artist','Artist'],['medium','Medium'],['dimensions','Dimensions'],['price','Price (INR)','number'],['year','Year'],['location','Location'],['description','Description','textarea']],
  collections:[['title','Collection name','required'],['description','Description','textarea'],['artworkIds','Artworks','artworks']],
  catalogs:[['title','Catalog name','required'],['description','Description','textarea'],['customerId','Customer (optional)','customers'],['inquiryId','Inquiry (optional)','inquiries'],['artworkIds','Artworks','artworks']],
  customers:[['title','Customer name','required'],['email','Email','email'],['phone','Phone','tel'],['address','Street address'],['city','City'],['region','State / region'],['postal','Postal code'],['country','Country'],['gstin','GSTIN (if registered)'],['notes','Notes','textarea']],
  inquiries:[['title','Inquiry title','required'],['customerId','Customer','customers'],['status','Status',['New','Contacted','Interested','Converted','Closed']],['source','Source',['Walk-in','Phone','Email','Social Media','Referral','Other']],['assignee','Assigned to','users'],['address','Street address'],['city','City'],['region','State / region'],['postal','Postal code'],['country','Country'],['artworkIds','Interested artworks','artworks'],['notes','Notes','textarea'],['attachments','Images and attachments','files']],
  tasks:[['title','Follow-up','required'],['inquiryId','Linked inquiry','inquiries'],['assignee','Assigned to','users'],['dueAt','Due date','date'],['status','Status',['Open','Done']]],
  reservations:[['title','Reservation name','required'],['artworkId','Artwork','availableArtworks'],['customerId','Customer','customers'],['inquiryId','Inquiry','inquiries'],['expiresAt','Reserve until','datetime-local']],
  invoices:[['title','Document number','required'],['customerId','Customer','customers'],['inquiryId','Linked inquiry','inquiries'],['artworkIds','Artworks','invoiceArtworks'],['taxRate','Tax rate (%)','number']],
  payments:[['title','Payment description','required'],['invoiceId','Invoice','invoices']],
  deliveries:[['title','Delivery name','required'],['invoiceId','Invoice','invoices'],['status','Status',['Packing','Dispatched','Delivered','Installed']],['tracking','Tracking reference'],['address','Delivery address','textarea'],['notes','Delivery / installation notes','textarea'],['attachments','Proof of delivery','files']],
  conversations:[['title','Conversation name','required'],['kind','Type',['direct','group']],['memberIds','Participants','members']],
  rooms:[['title','Room name','required'],['description','Description','textarea'],['memberIds','Invited members','roomMembers'],['artworkIds','Shared artworks','artworks'],['catalogIds','Shared catalogs','catalogsMulti'],['status','Status',['Active','Archived']],['attachments','Shared files','files']]
};
const names={artworks:'artwork',collections:'collection',catalogs:'catalog',customers:'customer',inquiries:'inquiry',tasks:'follow-up',reservations:'reservation',invoices:'invoice',payments:'payment request',deliveries:'delivery',conversations:'conversation',rooms:'private room'};
function nextInvoiceNumber(records,type){const prefix=`${type==='proforma'?'PI':'INV'}-${new Date().getFullYear()}-`;let n=1;while(records.some(r=>r.title===`${prefix}${String(n).padStart(3,'0')}`))n++;return `${prefix}${String(n).padStart(3,'0')}`;}
export function EntityForm({entity,record,initial={},onClose,onSaved}){
 const{state,mutate,toast,refresh}=useApp();
 const draft=state.drafts.find(d=>d.entity===entity&&(d.entityId||null)===(record?.id||null)&&(entity!=='invoices'||record||(d.data.documentType||'invoice')===(initial.documentType||'invoice')));
 const defaults={title:'',theme:'Ivory',status:({inquiries:'New',tasks:'Open',deliveries:'Packing',rooms:'Active'})[entity],source:'Walk-in',assignee:state.provider?state.workspace.ownerId:state.user.id,artworkIds:[],catalogIds:[],attachments:[],memberIds:state.provider?[]:[state.user.id],kind:'group',price:0,taxRate:0,country:'India',dueAt:new Date().toISOString().slice(0,10),expiresAt:new Date(Date.now()+3*86400000).toISOString().slice(0,16),...(entity==='invoices'?{title:`INV-${new Date().getFullYear()}-${String(state.invoices.length+1).padStart(3,'0')}`}:{})};
 const[value,set]=useState(()=>{const c=state.customers.find(x=>x.id===(initial.customerId||record?.customerId));return {...defaults,...(entity==='invoices'?{documentType:initial.documentType||'invoice',title:nextInvoiceNumber(state.invoices,initial.documentType),sellerName:state.workspace.name||state.workspace.title||'',sellerAddress:formatPartyAddress(state.workspace),sellerGstin:state.workspace.gstin||'',customerName:c?.title||'',customerAddress:formatPartyAddress(c),customerGstin:c?.gstin||''}:{}),...record,...initial,...draft?.data};});const[busy,setBusy]=useState(false);const[mediaBusy,setMediaBusy]=useState(false);const[draftStatus,setDraftStatus]=useState(draft?'Draft recovered':'');const changed=useRef(false);const timer=useRef();const saving=useRef(false);
 const changeMany=patch=>{changed.current=true;set(old=>({...old,...patch}));};
 const change=(key,v)=>{changed.current=true;set(old=>{let next={...old,[key]:v};if(key==='customerId'){const c=state.customers.find(x=>x.id===v);if(c)for(const k of ['address','city','region','postal','country'])next[k]=c[k]||'';if(entity==='invoices')Object.assign(next,{customerName:c?.title||'',customerAddress:formatPartyAddress(c),customerGstin:c?.gstin||''});}if(key==='documentType'&&!record)next.title=nextInvoiceNumber(state.invoices,v);return next;});};
 useEffect(()=>{if(!changed.current||saving.current)return;clearTimeout(timer.current);setDraftStatus('Saving draft…');timer.current=setTimeout(()=>api('action',{action:'draft.save',entity,entityId:record?.id,data:value}).then(()=>setDraftStatus('Draft saved')).catch(()=>setDraftStatus('Draft not saved — keep this form open')),600);return()=>clearTimeout(timer.current);},[value]);
 const close=async()=>{clearTimeout(timer.current);if(changed.current&&!saving.current){try{await api('action',{action:'draft.save',entity,entityId:record?.id,data:value});}catch(e){toast(e.message,'error');return;}}onClose();};
 const submit=async e=>{e.preventDefault();setBusy(true);saving.current=true;clearTimeout(timer.current);const result=await mutate({action:'save',entity,entityId:record?.id,data:value},`${label(names[entity])} saved`);if(result){await api('action',{action:'draft.delete',entity,entityId:record?.id}).catch(()=>{});await refresh();onSaved?.(result);onClose();}else saving.current=false;setBusy(false);};
 const options=(kind)=>kind==='users'||kind==='members'?state.users.filter(x=>x.role!=='guest'&&!x.disabled):kind==='roomMembers'?state.users.filter(x=>!x.disabled):kind==='availableArtworks'?state.artworks.filter(x=>x.status==='Available'):kind==='invoiceArtworks'?state.artworks.filter(x=>x.status!=='Sold'):kind==='catalogsMulti'?state.catalogs:kind==='invoices'?state.invoices.filter(x=>x.documentType!=='proforma'&&(entity==='payments'?x.status==='Issued':true)):state[kind]||[];
 return <Modal wide title={`${record?'Edit':'New'} ${entity==='invoices'&&value.documentType==='proforma'?'proforma invoice':names[entity]}`} onClose={close}><form onSubmit={submit}><div className="form-grid">{entity==='invoices'&&<><label className="full">Document type<select value={value.documentType||'invoice'} onChange={e=>change('documentType',e.target.value)} disabled={!!record}><option value="invoice">Invoice</option><option value="proforma">Proforma invoice (PI)</option></select></label><p className="full invoice-form-note">Add both billing addresses before issuing. GSTIN is optional for parties without GST registration. Issued details are kept as a permanent snapshot.</p></>}{schema[entity].map(([key,caption,kind='text'])=>{
  if(['artworks','invoiceArtworks','members','roomMembers','catalogsMulti'].includes(kind))return <div className="full" key={key}><MultiSelect label={caption} options={options(kind)} value={value[key]||[]} onChange={v=>change(key,v)}/></div>;
  if(kind==='files')return <div key={key} className="full"><label>{caption}</label><div className="row wrap"><FilePicker onUpload={f=>change(key,[...(value[key]||[]),f.id])} accept="image/jpeg,image/png,image/webp,application/pdf" label="Upload file"/><FilePicker camera onUpload={f=>change(key,[...(value[key]||[]),f.id])}/></div><AttachmentList ids={value[key]} onRemove={id=>change(key,value[key].filter(x=>x!==id))}/><small className="muted">Preview before saving. Camera availability depends on your device; uploads work everywhere.</small></div>;
  if(Array.isArray(kind)||['users','customers','inquiries','invoices','availableArtworks'].includes(kind))return <label key={key}>{caption}<select value={value[key]||''} onChange={e=>change(key,e.target.value)} required={['customerId','assignee','artworkId','invoiceId'].includes(key)&&entity!=='catalogs'}><option value="">Select {caption.toLowerCase()}</option>{(Array.isArray(kind)?kind:options(kind)).map(o=>typeof o==='string'?<option key={o}>{o}</option>:<option key={o.id} value={o.id}>{o.title||o.name}</option>)}</select></label>;
  return <label key={key} className={kind==='textarea'?'full':''}>{caption}{kind==='textarea'?<textarea rows={3} value={value[key]||''} onChange={e=>change(key,e.target.value)}/>:<input type={kind==='required'?'text':kind} required={kind==='required'||['date','datetime-local'].includes(kind)} value={value[key]??''} onChange={e=>change(key,e.target.value)} min={kind==='number'?0:undefined} max={key==='taxRate'?100:undefined} step={kind==='number'?'0.01':undefined}/>}</label>;
 })}{entity==='invoices'&&<InvoicePartyFields value={value} onChange={change}/>} {entity==='artworks'&&<div className="full"><ProductMedia value={value} onChange={changeMany} onBusyChange={setMediaBusy}/></div>}</div><footer className="modal-footer"><span className="draft-status">{draftStatus}</span><Button type="button" variant="secondary" onClick={close}>Close</Button><Button type="submit" icon={Save} busy={busy} disabled={mediaBusy}>Save {entity==='invoices'&&value.documentType==='proforma'?'PI':names[entity]}</Button></footer></form></Modal>;
}
export function NewRecordButton({entity,initial,children,onSaved}){const[open,set]=useState(false);return <><Button icon={Plus} onClick={()=>set(true)}>{children||`New ${names[entity]}`}</Button>{open&&<EntityForm entity={entity} initial={initial} onClose={()=>set(false)} onSaved={onSaved}/>}</>;}
export {names};
