import React, { createContext, useContext, useEffect, useRef, useState } from 'react';
import { X, ArrowUpRight, Search, Image as ImageIcon, Check, ChevronDown, Upload, Camera, LoaderCircle } from 'lucide-react';
export const Context=createContext(null);
export const useApp=()=>useContext(Context);
let apiScope=null;
export async function api(path,body){const started=apiScope,transition=['login','provider/login','logout','register','invitation/accept','provider/enter','provider/exit'].includes(path);const r=await fetch(`/api/${path}`,{method:body===undefined?'GET':'POST',headers:{...(body===undefined?{}:{'Content-Type':'application/json'}),...(started?{'X-Vayu-Context':started}:{})},body:body===undefined?undefined:JSON.stringify(body)});const d=await r.json();if(!transition&&started!==apiScope)throw new Error('Organization changed; an outdated response was discarded.');if(!r.ok){const error=new Error(d.error||'Unable to complete the request.');error.status=r.status;throw error;}if(transition)apiScope=null;const next=d.apiScope||d.state?.apiScope;if(next)apiScope=next;return d;}
export const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n||0);
export const date=x=>x?new Date(x).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—';
export const time=x=>new Date(x).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});
export const label=x=>x?.replace(/([A-Z])/g,' $1').replace(/[_.]/g,' ').replace(/^./,c=>c.toUpperCase())||'';
export const go=(view,id)=>{location.hash=`/${view}${id?`/${id}`:''}`;};
export function useRoute(){const read=()=>{const [view='overview',id]=location.hash.replace(/^#\/?/,'').split('/');return {view:view||'overview',id};};const[r,set]=useState(read);useEffect(()=>{const f=()=>set(read());addEventListener('hashchange',f);return()=>removeEventListener('hashchange',f);},[]);return r;}
export function Button({children,variant='',icon:Icon,busy,...props}){const accessibleName=props['aria-label']||(typeof children==='string'?children:typeof children?.props?.children==='string'?children.props.children:undefined);return <button {...props} aria-label={accessibleName} className={`button ${variant} ${props.className||''}`} disabled={busy||props.disabled}>{busy?<LoaderCircle size={16} className="spin"/>:Icon?<Icon size={16}/>:null}{children}</button>;}
export function Badge({children}){return <span className={`badge ${String(children).toLowerCase().replace(/[^a-z]+/g,'-')}`}>{children}</span>;}
export function Avatar({user,size=''}){return <span className={`avatar ${size}`} title={user?.name}>{user?.initials||user?.name?.split(' ').map(x=>x[0]).join('').slice(0,2)||'V'}</span>;}
export function Empty({title='Nothing here yet',text='Create your first record to get started.',action}){return <div className="empty"><ImageIcon size={32} strokeWidth={1}/><h3>{title}</h3><p>{text}</p>{action}</div>;}
export function PageHeading({eyebrow,title,description,children}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow||'YOUR WORKSPACE'}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div><div className="heading-actions">{children}</div></div>;}
export function SectionTitle({title,link,onClick}){return <div className="section-title"><h2>{title}</h2>{link&&<button className="text-button" onClick={onClick}>{link}<ArrowUpRight size={15}/></button>}</div>;}
export function SearchField({value,onChange,placeholder='Search…'}){return <div className="search-field"><Search size={17}/><input aria-label={placeholder} placeholder={placeholder} value={value} onChange={e=>onChange(e.target.value)}/>{value&&<button aria-label="Clear search" onClick={()=>onChange('')}><X size={14}/></button>}</div>;}
export function Modal({title,children,onClose,wide=false}){
  const ref=useRef(null),closeRef=useRef(onClose);closeRef.current=onClose;
  useEffect(()=>{const before=document.activeElement;const scroll=document.body.style.overflow;document.body.style.overflow='hidden';ref.current?.focus();const key=e=>{if([...document.querySelectorAll('[role="dialog"]')].at(-1)!==ref.current)return;if(e.key==='Escape')closeRef.current();if(e.key==='Tab'){const els=[...ref.current.querySelectorAll('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href]')].filter(x=>x.offsetParent!==null);if(!els.length){e.preventDefault();return;}const first=els[0],last=els.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=scroll;document.removeEventListener('keydown',key);before?.focus();};},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose();}}><section className={`modal ${wide?'wide':''}`} ref={ref} tabIndex={-1} role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button type="button" className="icon-button" onClick={onClose} aria-label="Close dialog"><X size={21}/></button></header>{children}</section></div>;
}
export function Confirm({title,text,onConfirm,onClose,danger=false}){const[busy,set]=useState(false);return <Modal title={title} onClose={onClose}><p className="modal-copy">{text}</p><footer className="modal-footer"><Button variant="secondary" onClick={onClose}>Cancel</Button><Button variant={danger?'danger':''} busy={busy} onClick={async()=>{set(true);try{await onConfirm();}finally{set(false);}}}>{title}</Button></footer></Modal>;}
export function ArtImage({art,className='',...props}){const scoped=useApp()?.resolveMedia,resolve=scoped||((s)=>s);if(scoped&&!art?.image)return <span role="img" aria-label={`${art?.title||'Artwork'} · no image`} className={`art-image platform-image-placeholder ${className}`}><ImageIcon size={28} strokeWidth={1}/></span>;return <img className={`art-image ${className}`} src={resolve(art?.image||'/art/quiet.svg')} alt={art?.title||'Artwork'} loading="lazy" {...props}/>;}
export async function uploadFile(file){if(file.size>10*1024*1024)throw new Error('Maximum file size is 10 MB.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});return api('upload',{name:file.name,mime:file.type,data});}
export function FilePicker({onUpload,onBusyChange,accept='image/jpeg,image/png,image/webp',camera=false,label:caption}){
  const{toast,refresh,uploadFile:scopedUpload}=useApp();
  const[busy,setBusy]=useState(false),[capture,setCapture]=useState(false),input=useRef();
  return <><input ref={input} type="file" className="sr-only" accept={accept} capture={camera?'environment':undefined} aria-label={caption||(camera?'Take photo':'Upload file')} onChange={async e=>{
    const file=e.target.files[0];if(!file)return;
    setBusy(true);onBusyChange?.(true);
    try{const f=await(scopedUpload||uploadFile)(file);await refresh();await onUpload(f);toast('File uploaded');}
    catch(e){toast(e.message,'error');}
    finally{setBusy(false);onBusyChange?.(false);if(input.current)input.current.value='';}
  }}/><Button type="button" variant="secondary" icon={camera?Camera:Upload} busy={busy} onClick={()=>camera&&navigator.mediaDevices?.getUserMedia?setCapture(true):input.current.click()}>{caption||(camera?'Take photo':'Upload image')}</Button>{capture&&<CameraCapture onClose={()=>setCapture(false)} onUpload={onUpload} onFallback={()=>{setCapture(false);input.current.click();}}/>}</>;
}
function CameraCapture({onClose,onUpload,onFallback}){
 const{toast,refresh,uploadFile:scopedUpload}=useApp();const video=useRef(null),stream=useRef(null),active=useRef(true);const[ready,setReady]=useState(false),[snapshot,setSnapshot]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const stop=()=>{stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;};
 useEffect(()=>()=>{active.current=false;stop();},[]);
 const start=async()=>{setBusy(true);setError('');setSnapshot('');try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1280}},audio:false});if(!active.current){s.getTracks().forEach(t=>t.stop());return;}stream.current=s;video.current.srcObject=s;await video.current.play();setReady(true);}catch{setError('Camera access is unavailable or was declined. You can upload an image instead.');}finally{setBusy(false);}};
 const capture=()=>{const v=video.current;if(!v?.videoWidth)return;const canvas=document.createElement('canvas'),ratio=Math.min(1,1600/v.videoWidth);canvas.width=v.videoWidth*ratio;canvas.height=v.videoHeight*ratio;canvas.getContext('2d').drawImage(v,0,0,canvas.width,canvas.height);setSnapshot(canvas.toDataURL('image/jpeg',.9));stop();setReady(false);};
 const attach=async()=>{setBusy(true);try{const name=`camera-${Date.now()}.jpg`;const f=scopedUpload?await scopedUpload(new File([Uint8Array.from(atob(snapshot.split(',')[1]),c=>c.charCodeAt(0))],name,{type:'image/jpeg'})):await api('upload',{name,mime:'image/jpeg',data:snapshot.split(',')[1]});await refresh();await onUpload(f);toast('Camera photo attached');onClose();}catch(e){toast(e.message,'error');}finally{setBusy(false);}};
 return <Modal title="Capture a photo" onClose={onClose}><div className="modal-body"><p>Your camera is used only after you start it. Review the photo before attaching it.</p>{snapshot?<img className="camera-preview" src={snapshot} alt="Captured photo preview"/>:<video ref={video} className="camera-preview" playsInline muted aria-label="Live camera preview"/>}{error&&<div className="inline-error">{error}</div>}<div className="row wrap">{snapshot?<><Button type="button" variant="secondary" onClick={start} busy={busy}>Retake</Button><Button type="button" onClick={attach} busy={busy}>Use photo</Button></>:ready?<Button type="button" icon={Camera} onClick={capture}>Capture photo</Button>:<Button type="button" icon={Camera} onClick={start} busy={busy}>Start camera</Button>}<Button type="button" variant="secondary" onClick={onFallback}>Upload instead</Button></div></div></Modal>;
}
export function AttachmentList({ids=[],onRemove}){const{state}=useApp();return <div className="attachments">{ids.map(id=>{const f=state.files.find(x=>x.id===id);return <div className="attachment" key={id}>{f?.mime?.startsWith('image/')?<img src={`/api/files/${id}`} alt={f?.name||'Attachment'}/>:<ImageIcon size={24}/>}<a href={`/api/files/${id}`} target="_blank" rel="noreferrer">{f?.name||'Attachment'}</a>{onRemove&&<button type="button" className="icon-button" aria-label="Remove attachment" onClick={()=>onRemove(id)}><X size={16}/></button>}</div>;})}</div>;}
export function MultiSelect({options,value=[],onChange,label:caption}){const missing=value.filter(id=>!options.some(o=>o.id===id));return <fieldset className="multi-select"><legend>{caption}</legend><div>{options.map(o=><label key={o.id}><input type="checkbox" checked={value.includes(o.id)} onChange={e=>onChange(e.target.checked?[...value,o.id]:value.filter(x=>x!==o.id))}/>{o.image&&<img src={o.image} alt=""/>}<span>{o.title||o.name}</span>{o.status&&<small>{o.status}</small>}</label>)}{missing.map(id=><label key={id}><input type="checkbox" checked onChange={()=>onChange(value.filter(x=>x!==id))}/><span>Unavailable record · {id.slice(0,8)}</span><small>Uncheck to remove</small></label>)}{!options.length&&!missing.length&&<p>No records available yet.</p>}</div></fieldset>;}
export function downloadJSON(data,name){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function readCSV(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quote&&text[i+1]==='"'){cell+='"';i++;}else quote=!quote;}else if(c===','&&!quote){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quote)throw new Error('CSV contains an unclosed quoted field.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);const headers=rows.shift()?.map(x=>x.trim().toLowerCase())||[];if(!headers.includes('title')||!headers.includes('price'))throw new Error('CSV needs title and price columns.');return rows.map((r,i)=>{if(r.length!==headers.length)throw new Error(`Row ${i+2} has the wrong number of columns.`);const o=Object.fromEntries(headers.map((h,j)=>[h,r[j]]));if(!o.title?.trim()||!o.price?.trim()||!Number.isFinite(Number(o.price))||Number(o.price)<0)throw new Error(`Check title and price on row ${i+2}.`);return o;});}
