import React,{useEffect,useMemo,useRef,useState} from 'react';
import {BookOpen,Images,Activity,Building2,LogOut,Plus,ArrowUpRight,ArrowLeft,Trash2,ShieldCheck,FileText} from 'lucide-react';
import {Context,Button,Modal,FilePicker,Empty,SearchField,date,ArtImage} from './lib.jsx';
import {Designer} from './catalog.jsx';
import {ProductMedia} from './product-media.jsx';
import {createCatalogRenderer} from './catalog-renderer.js';
import {GalleryInvoices} from './platform-invoices.jsx';

const ref=id=>id?`/api/files/${id}`:'';
const mediaId=src=>src?.match(/^\/api\/files\/([a-f0-9-]{36})$/)?.[1]||null;
const artwork=r=>({...r,image:ref(r.display_media_id||r.media_ids?.[0]),bannerImage:ref(r.banner_media_id||r.display_media_id||r.media_ids?.[0]),images:(r.media_ids||[]).map(ref),price:r.price_minor===null?null:Number(r.price_minor)/100});
const catalog=r=>({...r,theme:'Ivory',artworkIds:r.artworkIds||[],updatedAt:r.updated_at,versions:(r.versions||[]).slice().reverse().map(v=>({...v,number:v.version_number,fileId:v.media_id,createdAt:v.created_at,source:r.source==='uploaded'?'Uploaded':'Generated'}))});
const designBody=d=>({title:d.title,description:d.description||'',artworkIds:d.artworkIds,design:d.design});
const cursorQuery=(q,next)=>new URLSearchParams({limit:'30',...(q?{q}:{}),...(next||{})}).toString();
function Problem({error}){return error?<div className="platform-error" role="alert"><div><strong>{error.message}</strong>{error.status===401&&<a href="/auth/login">Sign in again</a>}{error.requestId&&<small>Support reference: {error.requestId}</small>}</div></div>:null;}

export function GalleryWorkspace({client,session,gallery,providerAccessId,onSwitchGallery,onSignOut}){
 const api=useMemo(()=>client.bindGallery(gallery.id),[client,gallery.id]);
 const[view,setView]=useState('catalogs'),[open,setOpen]=useState(null),[detail,setDetail]=useState(null),[draft,setDraft]=useState(null),[error,setError]=useState(null),[notice,setNotice]=useState(''),[revision,setRevision]=useState(0);
 const[products,setProducts]=useState([]),[next,setNext]=useState(null),[query,setQuery]=useState(''),[cache,setCache]=useState({}),[loading,setLoading]=useState(false);
 const detailRef=useRef(null),scopeAlive=useRef(true),searchGeneration=useRef(0),draftQueue=useRef(Promise.resolve()),lifecycle=useRef(new AbortController());
 useEffect(()=>()=>{scopeAlive.current=false;lifecycle.current.abort();},[]);
 const report=e=>{if(e.code!=='SCOPE_CHANGED'&&e.name!=='AbortError'&&scopeAlive.current)setError(e);};
 const toast=(message,type)=>{if(!scopeAlive.current)return;type==='error'?setError(new Error(message)):setNotice(message);};
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(timer);},[notice]);
 const remember=rows=>setCache(old=>({...old,...Object.fromEntries(rows.map(r=>[r.id,artwork(r)]))}));
 const receive=row=>{detailRef.current=catalog(row);setDetail(detailRef.current);remember(row.artworks||[]);return detailRef.current;};
 const loadProducts=async(q='',cursor=null)=>{const stamp=cursor?searchGeneration.current:++searchGeneration.current;try{const page=await api.galleryRequest(`inventory?${cursorQuery(q,cursor)}`);if(stamp!==searchGeneration.current)return;remember(page.items);setProducts(old=>cursor?[...old,...page.items.map(artwork)]:page.items.map(artwork));setNext(page.next);}catch(e){report(e);}};
 const searchProducts=q=>{setQuery(q);void loadProducts(q);};
 const refresh=async()=>{if(detailRef.current)receive(await api.galleryRequest(`catalogs/${detailRef.current.id}/detail`));};
 const openCatalog=async id=>{setLoading(true);setError(null);try{const [row,savedDraft]=await Promise.all([api.galleryRequest(`catalogs/${id}/detail`),api.galleryRequest(`catalogs/${id}/draft`)]);
   const valid=savedDraft.draft?.base_version===row.version?savedDraft.draft:null;
   if(savedDraft.draft&&!valid)setNotice('An older draft was not restored because the catalog changed. The latest saved design was opened.');
   const extra=(valid?.data.artworkIds||[]).filter(a=>!row.artworkIds.includes(a));
   for(let offset=0;offset<extra.length;offset+=8){remember(await Promise.all(extra.slice(offset,offset+8).map(a=>api.galleryRequest(`artworks/${a}/detail`))));}
   receive(row);setDraft(valid?.data||null);setOpen(id);setQuery('');await loadProducts('');
  }catch(e){report(e);}finally{if(scopeAlive.current)setLoading(false);}};
 const resolveMedia=src=>{const id=mediaId(src);return id?`/api/galleries/${gallery.id}/media/${id}/content${providerAccessId?`?access=${providerAccessId}`:''}`:src;};
 const imageCache=useRef(new Map());
 const loadImage=src=>{if(!imageCache.current.has(src)){const pending=new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('An image is unavailable. Check your access and reload.'));img.src=resolveMedia(src);});imageCache.current.set(src,pending);pending.catch(()=>imageCache.current.delete(src));}return imageCache.current.get(src);};
 const renderer=useMemo(()=>createCatalogRenderer({loadImage,formatPrice:a=>a.price_minor===null?'Price on request':new Intl.NumberFormat('en',{style:'currency',currency:a.currency}).format(Number(a.price_minor)/10**new Intl.NumberFormat('en',{style:'currency',currency:a.currency}).resolvedOptions().maximumFractionDigits),formatDimensions:d=>typeof d==='string'?d:[d.height,d.width,d.depth].filter(Boolean).join(' × ')+` ${d.unit||''}`}),[gallery.id,providerAccessId]);
 const pause=ms=>new Promise((resolve,reject)=>{const abort=()=>{clearTimeout(timer);reject(new DOMException('Workspace closed','AbortError'));};const timer=setTimeout(()=>{lifecycle.current.signal.removeEventListener('abort',abort);resolve();},ms);if(lifecycle.current.signal.aborted)abort();else lifecycle.current.signal.addEventListener('abort',abort,{once:true});});
 const waitJob=async(id,progress)=>{for(let i=0;i<100;i++){const job=await api.galleryRequest(`jobs/${id}`);if(job.status==='succeeded')return job;if(job.status==='dead')throw new Error(`Processing needs attention (${job.last_error_code||'job failed'}). Job: ${id}`);progress?.(job.status==='running'?'Generating your PDF…':'Waiting for processing…');await pause(3000);}throw new Error(`Processing is continuing. Check Activity for job ${id}.`);};
 const upload=async file=>{if(file.size>50*1024*1024)throw new Error('Maximum file size is 50 MB.');const checksum=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(b=>b.toString(16).padStart(2,'0')).join('');
  const intent=await api.galleryRequest('media/uploads',{body:{name:file.name,mime:file.type,bytes:file.size,checksum,purpose:file.type==='application/pdf'?'catalog':'artwork'}});
  const put=await fetch(intent.url,{method:'PUT',headers:intent.headers,body:file,credentials:'omit',redirect:'error',signal:lifecycle.current.signal});if(!put.ok)throw new Error('The upload did not complete. Please try again.');
  const job=await api.galleryRequest(`media/${intent.id}/complete`,{body:{}});await waitJob(job.jobId);
  const status=await api.galleryRequest(`media/${intent.id}/status`);if(status.state!=='ready')throw new Error('This file did not pass verification.');return {id:intent.id,name:status.name,mime:status.mime_type};
 };
 const saveArtwork=async(art,images)=>{const row=await api.galleryRequest(`artworks/${art.id}/media-order`,{body:{mediaIds:images.images.map(mediaId),displayMediaId:mediaId(images.image??art.image),bannerMediaId:mediaId(images.bannerImage??art.bannerImage)},version:art.version});remember([row]);setProducts(old=>old.map(a=>a.id===row.id?artwork(row):a));return artwork(row);};
 const mutate=async action=>{try{setError(null);if(action.entity==='catalogs'&&action.action==='save'){await draftQueue.current.catch(()=>{});return receive(await api.galleryRequest(`catalogs/${action.entityId}/design`,{body:designBody(action.data),version:detailRef.current.version}));}
  if(action.entity==='artworks'&&action.action==='save'){const art=cache[action.entityId];return await saveArtwork(art,{...art,...action.data});}throw new Error('This operation is not available in this workspace.');
 }catch(e){report(e);return null;}};
 const runtime={products,hasMore:!!next,searchProducts,loadMore:()=>loadProducts(query,next),renderPage:renderer.renderCatalogPage,back:()=>{setOpen(null);setDetail(null);detailRef.current=null;setDraft(null);setRevision(n=>n+1);},
  saveDraft:data=>{const current=detailRef.current;const operation=()=>api.galleryRequest(`catalogs/${current.id}/draft`,{body:designBody(data),version:current.version});const promise=draftQueue.current.then(operation,operation);draftQueue.current=promise;return promise;},
  generate:async(saved,progress)=>{const job=await api.galleryRequest(`catalogs/${saved.id}/generate`,{body:{artworkIds:saved.artworkIds},version:saved.version});await waitJob(job.jobId,progress);await refresh();},
  editArtwork:(art,close)=><MediaDialog art={cache[art.id]||art} onClose={close} save={saveArtwork}/>,
  versions:(c,close)=><Versions api={api} catalog={c} onClose={close} refresh={refresh}/>
 };
 const context={state:{artworks:Object.values(cache),drafts:draft?[{entity:'catalogs',entityId:open,data:draft}]:[],files:[]},session,mutate,toast,refresh,uploadFile:upload,resolveMedia,loadImage,catalogRuntime:runtime,catalogError:error,clearCatalogError:()=>setError(null)};
 return <Context.Provider value={context}><div className="gallery-platform"><aside className="gallery-sidebar"><strong className="gallery-wordmark">vayu.</strong><button className="gallery-switch" disabled={!!open} title={open?'Save and return to Catalog before switching galleries':undefined} onClick={onSwitchGallery}><Building2 size={18}/><span>{gallery.name}<small>Switch gallery</small></span></button>{providerAccessId&&<div className="gallery-provider"><ShieldCheck size={16}/>Provider access</div>}<nav aria-label="Gallery navigation">{[['catalogs','Catalog',BookOpen],['artworks','Artworks',Images],['invoices','Invoices & PI',FileText],['activity','Activity',Activity]].map(([key,name,Icon])=><button disabled={!!open} key={key} className={view===key?'active':''} onClick={()=>{setView(key);setError(null);}}><Icon size={18}/>{name}</button>)}</nav><div className="gallery-user"><span>{session.name}<small>{providerAccessId?'Provider':gallery.role}</small></span><button className="icon-button" aria-label="Sign out" disabled={!!open} onClick={onSignOut}><LogOut size={18}/></button></div></aside>
 <main className="gallery-content"><Problem error={error}/>{notice&&<div className="gallery-toast" role="status">{notice}</div>}{loading?<p role="status">Opening catalog…</p>:open&&detail?<Designer key={open} catalog={detail}/>:view==='catalogs'?<CatalogLibrary key={revision} api={api} open={openCatalog} report={report}/>:view==='artworks'?<ArtworkInventory api={api} report={report} remember={remember} saveArtwork={saveArtwork}/>:view==='invoices'?<GalleryInvoices api={api} gallery={gallery} canWrite={!!providerAccessId||['owner','admin','manager','staff'].includes(gallery.role)}/>:<JobActivity api={api} canAudit={!!providerAccessId||['owner','admin'].includes(gallery.role)} report={report}/>}</main></div></Context.Provider>;
}

function CatalogLibrary({api,open,report}){
 const[section,setSection]=useState('library');const[page,setPage]=useState({items:[],next:null}),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[create,setCreate]=useState(false),[name,setName]=useState(''),[remove,setRemove]=useState(null),[versions,setVersions]=useState(null);
 const load=async(next=null,signal)=>{const value=await api.galleryRequest(`catalog-library?section=${section}&${cursorQuery(query,next)}`,{signal});setPage(old=>next?{...value,items:[...old.items,...value.items]}:value);};
 useEffect(()=>{const abort=new AbortController(),timer=setTimeout(()=>{setBusy(true);load(null,abort.signal).catch(report).finally(()=>!abort.signal.aborted&&setBusy(false));},200);return()=>{abort.abort();clearTimeout(timer);};},[query,section]);
 const add=async(title,source='generated')=>api.galleryRequest('catalogs',{body:{title,source,design:{}}});
 return <div className="catalog-home"><header className="catalog-home-heading"><div><span className="eyebrow">YOUR COLLECTION, BEAUTIFULLY PRESENTED</span><h1>Catalog</h1><p>Design a collection. Keep every saved edition together.</p></div><div className="row wrap"><FilePicker label="Upload PDF" accept="application/pdf" onUpload={async f=>{const c=await add(f.name.replace(/\.pdf$/i,''),'uploaded');await api.galleryRequest(`catalogs/${c.id}/pdf`,{body:{mediaId:f.id}});await load();}}/><Button icon={Plus} onClick={()=>setCreate(true)}>Create catalog</Button></div></header><div className="catalog-home-toolbar"><nav className="catalog-sections" aria-label="Catalog sections">{[['library','Library'],['designer','Designer']].map(([key,label])=><button key={key} className={section===key?'active':''} aria-current={section===key?'page':undefined} onClick={()=>setSection(key)}>{label}</button>)}</nav><SearchField value={query} onChange={setQuery} placeholder="Search catalogs…"/></div>{busy&&<p role="status">Loading catalogs…</p>}<div className="catalog-records">{page.items.map(c=><article className="catalog-record" key={c.id}><div className="catalog-record-thumbnail" style={{background:c.design.background||'#e9e8df'}}><BookOpen size={28} strokeWidth={1.2}/></div><div className="catalog-record-copy"><h2><button onClick={()=>open(c.id)}>{c.title}</button></h2><p>{c.version_count} saved PDFs<span>·</span>{date(c.updated_at)}</p></div><span className="badge">{c.status}</span><div className="catalog-record-actions"><Button variant="secondary" onClick={()=>open(c.id)}>Edit design<ArrowUpRight size={15}/></Button><Button variant="ghost" onClick={async()=>{try{setVersions(catalog(await api.galleryRequest(`catalogs/${c.id}/detail`)));}catch(e){report(e);}}}>Versions</Button><button className="icon-button" aria-label={`Delete ${c.title}`} onClick={()=>setRemove(c)}><Trash2 size={16}/></button></div></article>)}</div>{!busy&&!page.items.length&&<Empty title={query?'No matching catalogs':'Your first collection starts here'} text="Choose artworks, shape the pages, and save an edition to your library." action={<Button onClick={()=>setCreate(true)}>Create catalog</Button>}/>} {page.next&&<Button variant="secondary" onClick={()=>load(page.next).catch(report)}>Load more catalogs</Button>}
 {create&&<Modal title="Create catalog" onClose={()=>!busy&&setCreate(false)}><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const c=await add(name.trim());setCreate(false);await open(c.id);}catch(e){report(e);}finally{setBusy(false);}}}><div className="modal-body"><label>Catalog name<input autoFocus required maxLength={200} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Summer collection"/></label><p>Choose your artworks and customize every page next.</p></div><footer className="modal-footer"><Button variant="secondary" type="button" onClick={()=>setCreate(false)}>Cancel</Button><Button busy={busy}>Choose artworks</Button></footer></form></Modal>}
 {remove&&<Modal title="Remove catalog from Library" onClose={()=>!busy&&setRemove(null)}><p className="modal-copy">“{remove.title}” will be archived. Its saved editions and activity history are retained.</p><footer className="modal-footer"><Button variant="secondary" onClick={()=>setRemove(null)}>Cancel</Button><Button busy={busy} variant="danger" onClick={async()=>{setBusy(true);try{await api.galleryRequest(`catalogs/${remove.id}/archive`,{body:{restore:false},version:remove.version});setRemove(null);await load();}catch(e){report(e);}finally{setBusy(false);}}}>Remove catalog</Button></footer></Modal>}
 {versions&&<Versions api={api} catalog={versions} onClose={()=>setVersions(null)} refresh={async()=>{setVersions(catalog(await api.galleryRequest(`catalogs/${versions.id}/detail`)));await load();}}/>}</div>;
}
function Versions({api,catalog:c,onClose,refresh}){const[error,setError]=useState(null);return <Modal wide title={`${c.title} · saved editions`} onClose={onClose}><div className="modal-body"><Problem error={error}/><FilePicker label="Upload PDF edition" accept="application/pdf" onUpload={async f=>{await api.galleryRequest(`catalogs/${c.id}/pdf`,{body:{mediaId:f.id}});await refresh();}}/><div className="version-list">{c.versions.slice().reverse().map(v=><div key={v.id}><FileText size={24}/><div><strong>Edition {v.number}</strong><small>{date(v.createdAt)}</small></div><Button variant="secondary" onClick={async()=>{try{const link=await api.galleryRequest(`media/${v.fileId}/download`,{body:{}});const a=document.createElement('a');a.href=link.url;a.rel='noreferrer';a.click();}catch(e){setError(e);}}}>Download PDF</Button></div>)}</div>{!c.versions.length&&<Empty title="No saved editions yet" text="Generate a PDF from the designer or upload an existing catalog."/>}</div></Modal>;}
function MediaDialog({art,onClose,save}){const[value,setValue]=useState(art),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[error,setError]=useState(null);return <Modal wide title={`${art.title} · images`} onClose={busy||uploading?()=>{}:onClose}><div className="modal-body"><Problem error={error}/><ProductMedia value={value} onChange={patch=>setValue(v=>({...v,...patch}))} onBusyChange={setUploading}/></div><footer className="modal-footer"><Button variant="secondary" disabled={busy||uploading} onClick={onClose}>Cancel</Button><Button busy={busy} disabled={uploading} onClick={async()=>{setBusy(true);try{await save(art,value);onClose();}catch(e){setError(e);}finally{setBusy(false);}}}>Save images</Button></footer></Modal>;}
function ArtworkInventory({api,report,remember,saveArtwork}){const[page,setPage]=useState({items:[],next:null}),[query,setQuery]=useState(''),[edit,setEdit]=useState(null),[create,setCreate]=useState(false),[busy,setBusy]=useState(false);const load=async(next=null,signal)=>{const data=await api.galleryRequest(`inventory?${cursorQuery(query,next)}`,{signal});remember(data.items);setPage(old=>next?{...data,items:[...old.items,...data.items]}:data);};useEffect(()=>{const controller=new AbortController(),timer=setTimeout(()=>load(null,controller.signal).catch(report),200);return()=>{clearTimeout(timer);controller.abort();};},[query]);return <><header className="catalog-home-heading"><div><h1>Artworks</h1><p>Build your inventory and arrange every view.</p></div><Button icon={Plus} onClick={()=>setCreate(true)}>Add artwork</Button></header><SearchField value={query} onChange={setQuery} placeholder="Search artworks…"/><div className="platform-artwork-grid">{page.items.map(row=><button key={row.id} onClick={()=>setEdit(artwork(row))}><ArtImage art={artwork(row)}/><strong>{row.title}</strong><small>{row.inventory_number} · {row.media_ids.length} images</small></button>)}</div>{!page.items.length&&<Empty title="Make room for your collection" text="Add an artwork, then upload front views, details and a banner image."/>}{page.next&&<Button variant="secondary" onClick={()=>load(page.next).catch(report)}>Load more artworks</Button>}{edit&&<MediaDialog art={edit} onClose={()=>setEdit(null)} save={async(a,v)=>{const saved=await saveArtwork(a,v);await load();return saved;}}/>}{create&&<Modal title="Add artwork" onClose={()=>!busy&&setCreate(false)}><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);try{const row=await api.galleryRequest('artworks',{body:data});setCreate(false);await load();setEdit(artwork({...row,media_ids:[]}));}catch(e){report(e);}finally{setBusy(false);}}}><div className="modal-body form-grid"><label>Title<input name="title" required maxLength={200}/></label><label>Inventory number<input name="inventory_number" required maxLength={200}/></label><label>Medium<input name="medium" maxLength={200}/></label><label>Currency<select name="currency"><option>USD</option><option>INR</option><option>EUR</option><option>GBP</option><option>AED</option><option>JPY</option></select></label><label className="full">Description<textarea name="description" maxLength={20000}/></label></div><footer className="modal-footer"><Button busy={busy}>Add artwork & images</Button></footer></form></Modal>}</>;}
function JobActivity({api,canAudit,report}){const[jobs,setJobs]=useState([]),[audit,setAudit]=useState([]);useEffect(()=>{let active=true;const load=async()=>{try{const rows=await api.galleryRequest('jobs');if(active)setJobs(rows.items);if(canAudit){const rows=await api.galleryRequest('audit');if(active)setAudit(rows.items);}}catch(e){report(e);}};void load();const timer=setInterval(load,15000);return()=>{active=false;clearInterval(timer);};},[]);return <><header className="catalog-home-heading"><div><h1>Activity</h1><p>Background processing{canAudit?' and the gallery activity log':''}.</p></div></header><h2>Processing</h2><div className="platform-activity">{jobs.map(j=><div key={j.id}><strong>{j.kind}</strong><span>{j.status}</span><small>{j.last_error_code||date(j.created_at)} · {j.id}</small></div>)}</div>{!jobs.length&&<p>No processing jobs yet.</p>}{canAudit&&<><h2>Gallery log</h2><p className="muted">Latest 100 events. Actor identities and before/after changes are retained.</p><div className="platform-activity">{audit.map(a=><details key={a.id}><summary>{a.action} · {a.entity_type}<small>{date(a.created_at)} · {a.actor_type}</small></summary><pre>{JSON.stringify({actorId:a.actor_id,entityId:a.entity_id,before:a.before_data,after:a.after_data},null,2)}</pre></details>)}</div></>}</>;}
