import React,{useEffect,useState} from 'react';
import {Plus,ArrowUpRight,ArrowLeft,Pencil,Trash2} from 'lucide-react';
import {Button,Modal,Empty,SearchField,Badge} from './lib.jsx';
import {InvoiceDocument,InvoicePartyFields,PrintInvoiceButton} from './invoice-document.jsx';

import {formatMinor as amount,minorToMajor,majorToMinor,invoiceTotals} from '../shared/invoice-money.mjs';
const queryString=values=>new URLSearchParams(Object.fromEntries(Object.entries(values).filter(([,v])=>v!==null&&v!==undefined&&v!==''))).toString();
function ErrorNotice({error}){return error?<div className="invoice-inline-error" role="alert">{error.message}{error.requestId&&<small> · Support reference: {error.requestId}</small>}</div>:null;}

export function GalleryInvoices({api,gallery,canWrite}){
 const[page,setPage]=useState({items:[],next:null}),[type,setType]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState(null),[selected,setSelected]=useState(null),[form,setForm]=useState(null),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[confirmIssue,setConfirmIssue]=useState(false);
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);setError(null);api.galleryRequest(`invoices?${queryString({documentType:type,q:query,limit:30})}`,{signal:controller.signal}).then(setPage).catch(e=>{if(!controller.signal.aborted)setError(e);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},150);return()=>{controller.abort();clearTimeout(timer);};},[api,type,query,revision]);
 const open=async id=>{setBusy(true);setError(null);try{setSelected(await api.galleryRequest(`invoices/${id}`));}catch(e){setError(e);}finally{setBusy(false);}};
 const changeStatus=async action=>{setBusy(true);setError(null);try{setSelected(await api.galleryRequest(`invoices/${selected.id}/${action}`,{body:{},version:selected.version}));setRevision(n=>n+1);setConfirmIssue(false);}catch(e){setError(e);setConfirmIssue(false);}finally{setBusy(false);}};
 return <section className="invoice-workspace"><header className="invoice-workspace-head"><div><span className="eyebrow">GALLERY BUSINESS</span><h1>Invoices & PI</h1><p>Prepare a proforma, confirm the details, and issue an invoice.</p></div>{canWrite&&<div className="row wrap"><Button variant="secondary" icon={Plus} onClick={()=>setForm({documentType:'proforma'})}>New PI</Button><Button icon={Plus} onClick={()=>setForm({documentType:'invoice'})}>New invoice</Button></div>}</header><ErrorNotice error={error}/>
 {selected?<><Button variant="ghost" icon={ArrowLeft} onClick={()=>{setSelected(null);setError(null);}}>All documents</Button><div className="row wrap" style={{margin:'20px 0'}}>{canWrite&&selected.status==='draft'&&<><Button variant="secondary" icon={Pencil} onClick={()=>setForm(selected)}>Edit draft</Button><Button onClick={()=>setConfirmIssue(true)}>Issue {selected.documentType==='proforma'?'PI':'invoice'}</Button></>}{canWrite&&selected.documentType==='proforma'&&selected.status==='issued'&&!selected.convertedInvoiceId&&<Button busy={busy} onClick={()=>changeStatus('convert')}>Convert to invoice</Button>}{selected.convertedInvoiceId&&<Button variant="secondary" onClick={()=>open(selected.convertedInvoiceId)}>Open linked invoice</Button>}{selected.proformaId&&<Button variant="secondary" onClick={()=>open(selected.proformaId)}>View source PI</Button>}<PrintInvoiceButton record={selected}/></div><InvoiceDocument record={selected}/><p className="invoice-form-note">Issued documents retain their billing details and artwork prices. A proforma is excluded from sales and payment requests.</p></>:<><div className="catalog-home-toolbar"><nav className="invoice-kind-filter" aria-label="Document type">{[['','All documents'],['invoice','Invoices'],['proforma','Proforma invoices (PI)']].map(([key,title])=><button className={type===key?'active':''} aria-pressed={type===key} key={key} onClick={()=>setType(key)}>{title}</button>)}</nav><SearchField value={query} onChange={setQuery} placeholder="Search document number or customer…"/></div>{loading?<p role="status">Loading documents…</p>:<><div className="invoice-list">{page.items.map(r=><button key={r.id} disabled={busy} onClick={()=>open(r.id)}><div><strong>{r.number||'Draft'} <Badge>{r.documentType==='proforma'?'PI':'Invoice'}</Badge></strong><small>{r.customerName||'Customer not added'} · {r.status}</small></div><div className="invoice-list-amount"><strong>{amount(r.totalMinor,r.currency)}</strong><small>{r.createdAt?new Date(r.createdAt).toLocaleDateString('en-IN'):''}</small></div><ArrowUpRight size={18}/></button>)}</div>{!page.items.length&&!error&&<Empty title={query?'No matching documents':'Your invoices start here'} text="Create an invoice or send a proforma for review."/>}{page.next&&<Button busy={busy} variant="secondary" onClick={async()=>{setBusy(true);try{const next=await api.galleryRequest(`invoices?${queryString({documentType:type,q:query,limit:30,...page.next})}`);setPage(old=>({...next,items:[...old.items,...next.items]}));}catch(e){setError(e);}finally{setBusy(false);}}}>Load more</Button>}</>}</>}
 {form&&<InvoiceEditor key={form.id||form.documentType} api={api} gallery={gallery} record={form} onClose={()=>setForm(null)} onSaved={r=>{setForm(null);setSelected(r);setRevision(n=>n+1);setError(null);}}/>}
 {confirmIssue&&<Modal title={`Issue ${selected.documentType==='proforma'?'proforma invoice':'invoice'}`} onClose={()=>!busy&&setConfirmIssue(false)}><div className="modal-body"><p>The server will assign a document number and lock the billing details, GSTINs and prices. Review the document before issuing.</p></div><footer className="modal-footer"><Button variant="secondary" onClick={()=>setConfirmIssue(false)} disabled={busy}>Keep draft</Button><Button busy={busy} onClick={()=>changeStatus('issue')}>Issue document</Button></footer></Modal>}
 </section>;
}

function InvoiceEditor({api,gallery,record,onClose,onSaved}){
 const[value,setValue]=useState(()=>({documentType:record.documentType||'invoice',currency:'INR',sellerName:gallery.name,sellerAddress:'',sellerGstin:'',customerId:null,customerName:'',customerAddress:'',customerGstin:'',notes:'',dueAt:'',items:[],...record})),[error,setError]=useState(null),[busy,setBusy]=useState(false),[picker,setPicker]=useState(null);
 useEffect(()=>{if(record.id)return;const controller=new AbortController();api.galleryRequest('invoices/options?limit=1',{signal:controller.signal}).then(data=>setValue(old=>({...old,sellerName:old.sellerName||data.seller.sellerName,sellerAddress:old.sellerAddress||data.seller.sellerAddress,sellerGstin:old.sellerGstin||data.seller.sellerGstin}))).catch(e=>{if(!controller.signal.aborted)setError(e);});return()=>controller.abort();},[api,record.id]);
 const change=(key,v)=>setValue(old=>({...old,[key]:v}));
 const changeItem=(index,key,v)=>setValue(old=>({...old,items:old.items.map((item,i)=>i===index?{...item,[key]:v}:item)}));
 const submit=async e=>{e.preventDefault();setBusy(true);setError(null);try{const body={documentType:value.documentType,currency:value.currency,sellerName:value.sellerName,sellerAddress:value.sellerAddress,sellerGstin:value.sellerGstin,customerId:value.customerId||null,customerName:value.customerName,customerAddress:value.customerAddress,customerGstin:value.customerGstin,notes:value.notes,dueAt:value.dueAt||null,items:value.items.map(({id,artworkId,description,quantity,unitPriceMinor,taxRateBps})=>({...(id?{id}:{}),artworkId:artworkId||null,description,quantity:Number(quantity),unitPriceMinor:Number(unitPriceMinor),taxRateBps:Number(taxRateBps)}))};onSaved(await api.galleryRequest(record.id?`invoices/${record.id}`:'invoices',{body,method:record.id?'PATCH':'POST',...(record.id?{version:record.version}:{})}));}catch(e){setError(e);}finally{setBusy(false);}};
 let totals=null,totalsError=null;try{totals=invoiceTotals(value.items.map(i=>({...i,quantity:Number(i.quantity)})));}catch(e){totalsError=e;}
 return <Modal wide title={`${record.id?'Edit':'New'} ${value.documentType==='proforma'?'proforma invoice':'invoice'}`} onClose={()=>!busy&&onClose()}><form onSubmit={submit}><div className="modal-body"><ErrorNotice error={error}/><p className="invoice-form-note invoice-form-section">Save a draft at any time. Both names and full addresses are required when issuing. Enter the tax rate that applies to this transaction.</p><div className="form-grid" style={{padding:0,marginBottom:24}}><label>Currency<select value={value.currency} disabled={value.items.length>0} onChange={e=>change('currency',e.target.value)}>{[...new Set([value.currency,'INR','USD','EUR','GBP'])].map(c=><option key={c}>{c}</option>)}</select></label><label>Due date <span className="muted">(optional)</span><input type="date" value={value.dueAt?.slice(0,10)||''} onChange={e=>change('dueAt',e.target.value)}/></label></div><div className="row wrap invoice-form-section"><Button type="button" variant="secondary" onClick={()=>setPicker('contacts')}>Choose saved customer</Button>{value.customerId&&<Button type="button" variant="ghost" onClick={()=>setValue(old=>({...old,customerId:null}))}>Unlink customer</Button>}<span className="invoice-form-note">Or enter customer details below.</span></div><InvoicePartyFields value={value} onChange={change}/>
 <section className="invoice-form-section" style={{marginTop:28}}><div className="row between wrap"><h3>Artworks & line items</h3><div className="row wrap"><Button type="button" variant="secondary" onClick={()=>setPicker('artworks')}>Add artwork</Button><Button type="button" variant="ghost" icon={Plus} onClick={()=>change('items',[...value.items,{id:crypto.randomUUID(),artworkId:null,description:'',quantity:1,unitPriceMinor:0,taxRateBps:0}])}>Add line</Button></div></div><div className="invoice-form-items">{value.items.map((item,i)=><div key={item.id||i}><label>Description<input required maxLength={2000} value={item.description} onChange={e=>changeItem(i,'description',e.target.value)}/></label><label>Quantity<input type="number" min="1" max="10000" step="1" required value={item.quantity} onChange={e=>changeItem(i,'quantity',e.target.value)}/></label><label>Unit price<MinorInput label={`Unit price for ${item.description||`line ${i+1}`}`} value={item.unitPriceMinor} currency={value.currency} onChange={n=>changeItem(i,'unitPriceMinor',n)}/></label><label>Tax %<MinorInput label={`Tax percent for line ${i+1}`} value={item.taxRateBps} currency="INR" max={10000} onChange={n=>changeItem(i,'taxRateBps',n)}/></label><button type="button" className="icon-button danger-text" aria-label={`Remove ${item.description||`line ${i+1}`}`} onClick={()=>change('items',value.items.filter((_,index)=>index!==i))}><Trash2 size={16}/></button></div>)}</div>{!value.items.length&&<p className="invoice-form-note">Choose an artwork or add a line item to begin.</p>}<ErrorNotice error={totalsError}/>{totals&&<div className="invoice-document-totals"><div><span>Subtotal</span><span>{amount(totals.subtotalMinor,value.currency)}</span></div><div><span>Tax</span><span>{amount(totals.taxMinor,value.currency)}</span></div><div className="invoice-grand-total"><strong>Total</strong><strong>{amount(totals.totalMinor,value.currency)}</strong></div></div>}</section><label>Notes & terms<textarea maxLength={20000} rows={3} value={value.notes} onChange={e=>change('notes',e.target.value)}/></label></div><footer className="modal-footer"><span className="invoice-form-note">Number assigned when issued</span><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>Cancel</Button><Button busy={busy} disabled={!!totalsError}>Save draft</Button></footer></form>
 {picker&&<InvoicePicker api={api} kind={picker} currency={value.currency} onClose={()=>setPicker(null)} onSelect={row=>{if(picker==='contacts')setValue(old=>({...old,customerId:row.id,customerName:row.name,customerAddress:row.address,customerGstin:row.gstin||''}));else setValue(old=>({...old,items:[...old.items,{id:crypto.randomUUID(),artworkId:row.id,description:row.title,quantity:1,unitPriceMinor:Number(row.priceMinor||0),taxRateBps:0}]}));setPicker(null);}}/>}</Modal>;
}

function InvoicePicker({api,kind,currency,onSelect,onClose}){
 const[query,setQuery]=useState(''),[page,setPage]=useState({items:[],next:null}),[error,setError]=useState(null),[loading,setLoading]=useState(true);
 const receive=(data,append=false)=>setPage(old=>({items:[...(append?old.items:[]),...data[kind]],next:data[`${kind}Next`]}));
 useEffect(()=>{const controller=new AbortController();const timer=setTimeout(()=>{setLoading(true);api.galleryRequest(`invoices/options?${queryString({kind,q:query,limit:30})}`,{signal:controller.signal}).then(data=>receive(data)).catch(e=>{if(!controller.signal.aborted)setError(e);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});},150);return()=>{controller.abort();clearTimeout(timer);};},[api,kind,query]);
 return <Modal title={kind==='contacts'?'Choose customer':'Choose artwork'} onClose={onClose}><div className="modal-body"><SearchField value={query} onChange={setQuery} placeholder={`Search ${kind==='contacts'?'customers':'artworks'}…`}/><ErrorNotice error={error}/>{loading?<p role="status">Loading…</p>:<><div className="invoice-picker-results">{page.items.map(r=><button key={r.id} disabled={kind==='artworks'&&r.currency!==currency} onClick={()=>onSelect(r)}><span>{r.name||r.title}</span>{kind==='artworks'&&<small>{r.currency!==currency?`Priced in ${r.currency}`:r.priceMinor===null?'Set price in draft':amount(r.priceMinor,r.currency)}</small>}</button>)}</div>{!page.items.length&&<p className="invoice-form-note">No matching records. You can enter the details manually.</p>}{page.next&&<Button variant="secondary" onClick={async()=>{setError(null);try{receive(await api.galleryRequest(`invoices/options?${queryString({kind,q:query,limit:30,...page.next})}`),true);}catch(e){setError(e);}}}>Load more</Button>}</>}</div></Modal>;
}


function MinorInput({value,currency,onChange,label,max=1_000_000_000_000}){
 return <input aria-label={label} type="text" inputMode="decimal" required defaultValue={minorToMajor(value,currency)} onChange={e=>{
  try{const n=majorToMinor(e.target.value,currency);if(n===null){e.target.setCustomValidity('Enter an amount.');return;}if(n>max)throw new RangeError('Amount exceeds the supported limit.');e.target.setCustomValidity('');onChange(n);}catch(error){e.target.setCustomValidity(error.message);}
 }}/>;
}
