import React,{useEffect,useRef,useState} from 'react';
import {Upload,Trash2,ArrowLeft,ArrowRight,WandSparkles,ImagePlus} from 'lucide-react';
import {Button,Modal,FilePicker,useApp,uploadFile} from './lib.jsx';
import {productImages} from '../shared/catalog-design.mjs';
import {loadImage} from './catalog-renderer.js';
import {removeConnectedBackground} from './image-tools.mjs';

export function ProductGallery({art}){const images=productImages(art),[selected,setSelected]=useState(art.image||images[0]);useEffect(()=>setSelected(art.image||images[0]),[art.id,art.image]);return <div className="product-gallery"><img className="product-gallery-main" src={images.includes(selected)?selected:images[0]||'/art/quiet.svg'} alt={art.title}/>{images.length>1&&<div className="product-gallery-strip">{images.map((src,i)=><button type="button" key={src} className={src===selected?'active':''} aria-label={`View product image ${i+1}`} onClick={()=>setSelected(src)}><img src={src} alt=""/></button>)}</div>}</div>;}
export function ProductMedia({value,onChange,onBusyChange=()=>{}}){const{toast,refresh,uploadFile:scopedUpload,resolveMedia=(s)=>s}=useApp(),input=useRef(),images=productImages(value),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[edit,setEdit]=useState(null);const update=imgs=>onChange({images:imgs,image:imgs.includes(value.image)?value.image:imgs[0]||'',bannerImage:imgs.includes(value.bannerImage)?value.bannerImage:imgs[0]||''});
 const add=src=>{if(images.length>=30){toast('Each product can hold up to 30 images.','error');return;}update([...images,src].filter((x,i,a)=>a.indexOf(x)===i));};
 const batch=async files=>{if(files.length+images.length>30){toast('Each product can hold up to 30 images.','error');return;}setBusy(true);onBusyChange(true);const added=[],failed=[];for(let i=0;i<files.length;i++){setProgress(`Uploading ${i+1} of ${files.length}`);try{const f=await (scopedUpload||uploadFile)(files[i]);added.push(`/api/files/${f.id}`);}catch(e){failed.push(`${files[i].name}: ${e.message}`);}}if(added.length){update([...images,...added]);await refresh();}setBusy(false);onBusyChange(false);setProgress('');if(failed.length)toast(`${added.length} images added. ${failed.join(' ')}`,'error');else toast(`${added.length} images added to this product`);};
 const move=(i,step)=>{const next=[...images];[next[i],next[i+step]]=[next[i+step],next[i]];update(next);};
 return <section className="product-media-editor"><div className="row between wrap"><div><h3>Product images</h3><p className="muted">Upload multiple views together. Choose the display image and catalog banner.</p></div><span>{images.length} / 30</span></div><div className="row wrap"><input hidden type="file" ref={input} multiple accept="image/jpeg,image/png,image/webp" aria-label="Choose multiple product images" onChange={e=>{batch([...e.target.files]);e.target.value='';}}/><Button type="button" variant="secondary" icon={Upload} busy={busy} onClick={()=>input.current.click()}>Bulk image upload</Button><FilePicker camera onUpload={f=>add(`/api/files/${f.id}`)}/></div>{progress&&<p role="status">{progress}</p>}<div className="product-media-grid">{images.map((src,i)=><article key={src}><div className="transparency-grid"><img src={resolveMedia(src)} alt={`Product image ${i+1}`}/></div><div className="media-choices"><label><input type="radio" name="display-image" checked={value.image===src||!value.image&&i===0} onChange={()=>onChange({images,image:src})}/>Display image</label><label><input type="radio" name="banner-image" checked={value.bannerImage===src||!value.bannerImage&&i===0} onChange={()=>onChange({images,bannerImage:src})}/>Banner image</label></div><div className="row between"><button className="icon-button" type="button" disabled={!i||busy} aria-label={`Move image ${i+1} earlier`} onClick={()=>move(i,-1)}><ArrowLeft size={15}/></button><button className="text-button" type="button" disabled={busy} onClick={()=>setEdit(src)}><WandSparkles size={14}/>Edit</button><button className="icon-button" type="button" disabled={i===images.length-1||busy} aria-label={`Move image ${i+1} later`} onClick={()=>move(i,1)}><ArrowRight size={15}/></button><button className="icon-button danger-text" type="button" disabled={busy} aria-label={`Remove image ${i+1}`} onClick={()=>update(images.filter(s=>s!==src))}><Trash2 size={15}/></button></div></article>)}</div>{!images.length&&<div className="media-empty"><ImagePlus size={28}/><p>Add a front view, details, and a banner image.</p></div>}{edit&&<ImageEditor src={edit} onClose={()=>setEdit(null)} onSaved={src=>{add(src);setEdit(null);}}/>}</section>;
}
export function ImageEditor({src,onClose,onSaved}){const{toast,refresh,uploadFile:scopedUpload,loadImage:scopedLoadImage}=useApp(),canvas=useRef(),original=useRef(),mask=useRef(),history=useRef([]),dragging=useRef(false),last=useRef(null);const[tolerance,setTolerance]=useState(35),[feather,setFeather]=useState(8),[brush,setBrush]=useState(30),[mode,setMode]=useState('pick'),[shadow,setShadow]=useState(false),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[picked,setPicked]=useState(null),[error,setError]=useState('');
 const redraw=()=>{if(!mask.current)return;const c=canvas.current,ctx=c.getContext('2d'),temp=document.createElement('canvas');temp.width=c.width;temp.height=c.height;temp.getContext('2d').putImageData(mask.current,0,0);ctx.clearRect(0,0,c.width,c.height);ctx.save();if(shadow){ctx.shadowColor='#00000070';ctx.shadowBlur=18;ctx.shadowOffsetY=10;}ctx.drawImage(temp,0,0);ctx.restore();};
 useEffect(()=>{let active=true;(scopedLoadImage||loadImage)(src).then(img=>{if(!active)return;const c=canvas.current,scale=Math.min(1,1600/Math.max(img.width,img.height));c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);original.current=c.getContext('2d').getImageData(0,0,c.width,c.height);mask.current=new ImageData(new Uint8ClampedArray(original.current.data),c.width,c.height);setReady(true);}).catch(e=>setError(e.message));return()=>{active=false;};},[src]);
 useEffect(redraw,[shadow,revision,ready]);
 const remember=()=>{history.current.push(new Uint8ClampedArray(mask.current.data));if(history.current.length>8)history.current.shift();};
 const coords=e=>{const r=canvas.current.getBoundingClientRect();return [Math.max(0,Math.min(canvas.current.width-1,Math.floor((e.clientX-r.left)/r.width*canvas.current.width))),Math.max(0,Math.min(canvas.current.height-1,Math.floor((e.clientY-r.top)/r.height*canvas.current.height)))];};
 const stroke=(x,y)=>{const c=canvas.current,r=brush/2*(c.width/700),data=mask.current.data;for(let py=Math.max(0,Math.floor(y-r));py<Math.min(c.height,y+r);py++)for(let px=Math.max(0,Math.floor(x-r));px<Math.min(c.width,x+r);px++){if((px-x)**2+(py-y)**2>r*r)continue;const i=(py*c.width+px)*4;data[i+3]=mode==='restore'?original.current.data[i+3]:0;}redraw();};
 const pointer=e=>{if(!ready)return;e.preventDefault();const[x,y]=coords(e);if(mode==='pick'){const i=(y*canvas.current.width+x)*4;setPicked({color:[...original.current.data.slice(i,i+3)],start:y*canvas.current.width+x});return;}remember();dragging.current=true;last.current=[x,y];e.currentTarget.setPointerCapture(e.pointerId);stroke(x,y);};
 const remove=()=>{remember();const c=canvas.current;mask.current=new ImageData(removeConnectedBackground(mask.current.data,c.width,c.height,{tolerance,feather,...(picked||{})}),c.width,c.height);setRevision(r=>r+1);};
 const save=async()=>{setBusy(true);try{redraw();const blob=await new Promise(resolve=>canvas.current.toBlob(resolve,'image/png'));if(!blob)throw new Error('Could not save this image.');const file=await (scopedUpload||uploadFile)(new File([blob],`product-cutout-${Date.now()}.png`,{type:'image/png'}));await refresh();const result=await onSaved(`/api/files/${file.id}`);if(result!==false)toast('Edited image added. Original image preserved.');}catch(e){toast(e.message,'error');}finally{setBusy(false);}};
 return <Modal wide title="Remove background & edit image" onClose={onClose}><div className="image-editor-layout"><div className="image-editor-stage transparency-grid"><canvas ref={canvas} aria-label="Image editing canvas. Click a background area to sample its color." onPointerDown={pointer} onPointerMove={e=>{if(!dragging.current)return;const[x,y]=coords(e),[lx,ly]=last.current,steps=Math.max(1,Math.ceil(Math.hypot(x-lx,y-ly)/Math.max(1,brush/5)));for(let j=1;j<=steps;j++)stroke(lx+(x-lx)*j/steps,ly+(y-ly)*j/steps);last.current=[x,y];}} onPointerUp={()=>{dragging.current=false;setRevision(r=>r+1);}} onPointerCancel={()=>{dragging.current=false;}}/>{error&&<p className="inline-error">{error}</p>}</div><aside className="image-editor-controls"><p>Best for plain backgrounds. Click a background color, then remove it. Use the brushes to refine complex edges.</p><label>Tool<select value={mode} onChange={e=>setMode(e.target.value)}><option value="pick">Pick background color</option><option value="erase">Erase brush</option><option value="restore">Restore brush</option></select></label><label>Color tolerance · {tolerance}<input type="range" min="0" max="150" value={tolerance} onChange={e=>setTolerance(+e.target.value)}/></label><label>Edge softness · {feather}<input type="range" min="0" max="40" value={feather} onChange={e=>setFeather(+e.target.value)}/></label><Button type="button" disabled={!ready} icon={WandSparkles} onClick={remove}>Remove background</Button><small>{picked?'Using the color you picked.':'Using the top-left background color.'}</small><label>Brush size · {brush}<input type="range" min="5" max="150" value={brush} onChange={e=>setBrush(+e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={shadow} onChange={e=>setShadow(e.target.checked)}/>Add soft shadow</label><div className="row wrap"><Button type="button" variant="secondary" disabled={!history.current.length} onClick={()=>{mask.current.data.set(history.current.pop());setRevision(r=>r+1);}}>Undo</Button><Button type="button" variant="secondary" disabled={!ready} onClick={()=>{remember();mask.current.data.set(original.current.data);setPicked(null);setRevision(r=>r+1);}}>Reset</Button></div><small>The checkerboard is transparent. Your original stays in the product gallery.</small></aside></div><footer className="modal-footer"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="button" busy={busy} disabled={!ready} onClick={save}>Save as new image</Button></footer></Modal>;
}
