import React,{useEffect,useState} from 'react';
import {Building2,Users,ShieldCheck,ArrowUpRight,Plus,Settings,Activity,CreditCard,LogOut,ChevronRight,ArrowLeft,Check,Copy} from 'lucide-react';
import {useApp,Button,Badge,Avatar,SearchField,Modal,Confirm,Empty,api,go,date} from './lib.jsx';
import {ActivityLog} from './admin.jsx';
import './provider.css';

const allowanceLabels={seats:'Employee seats',guests:'Guest accounts',artworks:'Products',catalogs:'Catalogs',storageMB:'Storage (MB)',rooms:'Private rooms',generations:'PDF generations / month'};
const features={inventory:'Inventory',collections:'Collections',catalogs:'Catalog',customers:'Customers',inquiries:'Inquiries',tasks:'Follow-ups',invoices:'Invoices',payments:'Payments',reservations:'Reservations',deliveries:'Delivery',reports:'Reports',conversations:'Direct & group messages',rooms:'Private rooms',audit:'Admin activity history',import:'Bulk CSV import'};
export function ProviderConsole(){
 const{state,providerMutate,openOrganization,providerLogin,logout}=useApp();
 const[section,setSection]=useState('organizations'),[search,setSearch]=useState(''),[status,setStatus]=useState('all'),[create,setCreate]=useState(false),[edit,setEdit]=useState(null),[plan,setPlan]=useState(null),[staff,setStaff]=useState(false),[toggle,setToggle]=useState(null),[opening,setOpening]=useState(null);
 const rows=state.organizations.filter(w=>(status==='all'||w.status===status)&&`${w.name} ${w.owner} ${w.plan}`.toLowerCase().includes(search.toLowerCase()));
 const sections=[['organizations','Organizations',Building2],['plans','Plans & allowances',CreditCard],['activity','Activity history',Activity],['team','Provider team',ShieldCheck]];
 const open=async id=>{setOpening(id);try{await openOrganization(id);}finally{setOpening(null);}};
 return <div className="provider-shell"><aside className="provider-sidebar"><div className="provider-brand">vayu<span>.</span><small>PROVIDER CONSOLE</small></div><nav aria-label="Provider navigation">{sections.map(([key,title,Icon])=><button key={key} className={section===key?'active':''} onClick={()=>setSection(key)}><Icon size={19}/>{title}</button>)}</nav><div className="provider-identity"><Avatar user={state.user}/><div><strong>{state.user.name}</strong><small>{state.user.providerRole==='owner'?'Provider owner':'Super admin'}</small></div><button className="icon-button" aria-label="Sign out of provider console" onClick={logout}><LogOut size={17}/></button></div></aside>
 <div className="provider-body"><header className="provider-topbar"><span>Vayu platform <ChevronRight size={14}/><strong>{sections.find(s=>s[0]===section)?.[1]}</strong></span><Badge>Local preview</Badge></header><main className="provider-main">
 {section==='organizations'&&<><div className="provider-heading"><div><span className="eyebrow">YOUR CUSTOMERS</span><h1>Organizations</h1><p>A clear view of every business you support.</p></div><Button icon={Plus} onClick={()=>setCreate(true)}>Create organization</Button></div><div className="provider-metrics"><div><small>Organizations</small><strong>{state.organizations.length}</strong></div><div><small>Active organizations</small><strong>{state.organizations.filter(w=>w.status==='active'&&w.subscription==='active').length}</strong></div><div><small>Active employees</small><strong>{state.organizations.filter(w=>w.status==='active'&&w.subscription==='active').reduce((n,w)=>n+w.employeeCount,0)}</strong></div><div><small>Stored catalogs</small><strong>{state.organizations.reduce((n,w)=>n+w.usage.catalogs,0)}</strong></div></div><div className="provider-toolbar"><SearchField value={search} onChange={setSearch} placeholder="Search organizations, owners or plans…"/><select aria-label="Organization status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="suspended">Suspended</option></select><span>{rows.length} organizations</span></div><div className="provider-organizations">{rows.map(w=><article key={w.id} className="provider-organization"><span className="organization-initial">{w.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div className="organization-name"><h2>{w.name}</h2><p>{w.owner} · {w.kind||'Organization'}</p></div><div className="organization-plan"><strong>{w.plan}</strong><small>Version {w.limits.version||1}{w.allowanceOverride?' · custom allowance':''}</small></div><div className="organization-seats"><strong>{w.team.active+w.team.reserved} / {w.limits.seats} seats</strong><small>{w.team.reserved?`${w.team.reserved} invitation${w.team.reserved===1?'':'s'} pending`:`${w.usage.catalogs} catalogs`}</small></div><Badge>{w.status==='suspended'?'Suspended':w.subscription}</Badge><div className="row"><Button variant="secondary" busy={opening===w.id} disabled={!!opening} onClick={()=>open(w.id)} aria-label={`Open organization ${w.name}`}>Open<ArrowUpRight size={15}/></Button><button className="icon-button" title="Manage organization" aria-label={`Manage organization ${w.name}`} onClick={()=>setEdit(w)}><Settings size={17}/></button></div></article>)}</div>{!rows.length&&<Empty title="No matching organizations" text="Try another search or create an organization."/>}<p className="provider-note"><ShieldCheck size={16}/>Open an organization to manage its records, employees, messages and private rooms. Provider access is recorded.</p></>}
 {section==='plans'&&<><div className="provider-heading"><div><span className="eyebrow">SUBSCRIPTIONS</span><h1>Plans & allowances</h1><p>Set the features and capacity each organization receives.</p></div></div><div className="notice">Changes create a new plan version. Existing organizations keep their current version until you assign the new one. Billing remains simulated in this local preview.</div><div className="provider-plans">{Object.values(state.plans).map(p=><article className="panel" key={p.id}><div className="row between"><h2>{p.name}</h2><Badge>Version {p.version}</Badge></div><div className="provider-seat-total">{p.seats}<small>employee seats</small></div><dl>{['artworks','catalogs','storageMB','rooms','generations','guests'].map(k=><div key={k}><dt>{allowanceLabels[k]}</dt><dd>{p[k]}</dd></div>)}</dl><p className="muted">{p.features.length} enabled features</p><Button variant="secondary" icon={Settings} onClick={()=>setPlan(p)}>Edit next version</Button></article>)}</div></>}
 {section==='activity'&&<ActivityLog/>}
 {section==='team'&&<><div className="provider-heading"><div><span className="eyebrow">PLATFORM ACCESS</span><h1>Provider team</h1><p>These accounts manage customer organizations and do not consume customer seats.</p></div>{state.user.providerRole==='owner'&&<Button icon={Plus} onClick={()=>setStaff(true)}>Add provider admin</Button>}</div><div className="notice">Provider profiles are local review identities. Production login and MFA must be connected before public access.</div><div className="panel team-list">{state.accounts.map(p=><div key={p.id}><Avatar user={p}/><div><strong>{p.name}</strong><small>{p.email}</small></div><Badge>{p.disabled?'Disabled':p.providerRole==='owner'?'Owner':'Super admin'}</Badge>{p.id!==state.user.id&&p.providerRole!=='owner'&&state.user.providerRole==='owner'&&<Button variant="secondary" onClick={()=>setToggle(p)}>{p.disabled?'Enable':'Disable'}</Button>}</div>)}</div><label className="provider-profile-switch">Review another provider profile<select value={state.user.id} onChange={e=>providerLogin(e.target.value)}>{state.accounts.filter(p=>!p.disabled).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></>}
 </main><footer className="provider-footer">Vayu provider workspace <span>Local data · No live billing</span></footer></div>
 {create&&<OrganizationCreate onClose={()=>setCreate(false)} onSave={async data=>{const r=await providerMutate({action:'organization.create',data},'Organization created');if(r)setCreate(false);}} plans={state.plans}/>}
 {edit&&<OrganizationEdit organization={edit} plans={state.planVersions} onClose={()=>setEdit(null)} onSave={async data=>{const r=await providerMutate({action:'organization.update',entityId:edit.id,data},'Organization updated');if(r)setEdit(null);}}/>}
 {plan&&<PlanEdit plan={plan} onClose={()=>setPlan(null)} onSave={async data=>{const r=await providerMutate({action:'plan.save',entityId:plan.id,data},'New plan version created');if(r)setPlan(null);}}/>}
 {staff&&<Modal title="Add provider admin" onClose={()=>setStaff(false)}><form onSubmit={async e=>{e.preventDefault();if(await providerMutate({action:'provider.add',data:Object.fromEntries(new FormData(e.target))},'Local provider admin created'))setStaff(false);}}><div className="form-grid"><p className="full muted">This local profile will have management access to every organization.</p><label>Name<input name="name" required maxLength={100}/></label><label>Email<input name="email" type="email" required/></label></div><footer className="modal-footer"><Button>Add local provider admin</Button></footer></form></Modal>}
 {toggle&&<Confirm title={toggle.disabled?'Enable provider access':'Disable provider access'} text={`${toggle.name} will ${toggle.disabled?'regain':'lose'} access to the provider console and organization data.`} onClose={()=>setToggle(null)} onConfirm={async()=>{if(await providerMutate({action:'provider.update',entityId:toggle.id,data:{disabled:!toggle.disabled}},'Provider access updated'))setToggle(null);}}/>}
 </div>;
}
function OrganizationCreate({plans,onClose,onSave}){const[busy,setBusy]=useState(false);return <Modal title="Create organization" onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));setBusy(true);try{await onSave(data);}finally{setBusy(false);}}}><div className="form-grid"><label className="full">Organization name<input name="name" required maxLength={100} placeholder="e.g. Horizon Studio"/></label><label>Business type<select name="kind"><option>Studio</option><option>Store</option><option>Organization</option></select></label><label>Plan<select name="plan">{Object.values(plans).map(p=><option key={p.id} value={p.name}>{p.name} · {p.seats} seats</option>)}</select></label><label>Owner name<input name="ownerName" required maxLength={100}/></label><label>Owner email<input type="email" name="email" required/></label><p className="full muted">Creates an empty local organization and owner profile. No email is sent and no payment is collected.</p></div><footer className="modal-footer"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button busy={busy}>Create organization</Button></footer></form></Modal>;}
function OrganizationEdit({organization:w,plans,onClose,onSave}){
 const[custom,setCustom]=useState(!!w.allowanceOverride),[busy,setBusy]=useState(false);
 return <Modal wide title={`Manage ${w.name}`} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const fields=Object.fromEntries(new FormData(e.target));const data={name:fields.name,status:fields.status,subscription:fields.subscription,planVersionId:fields.planVersionId,reason:fields.reason,clearOverride:!custom,...(custom?{limits:Object.fromEntries(Object.keys(allowanceLabels).map(k=>[k,Number(fields[k])])),expiresAt:fields.expiresAt?new Date(fields.expiresAt).toISOString():null}:{})};setBusy(true);try{await onSave(data);}finally{setBusy(false);}}}><div className="form-grid"><label className="full">Organization name<input name="name" required defaultValue={w.name} maxLength={100}/></label><label>Plan version<select name="planVersionId" defaultValue={w.planVersionId}>{plans.map(p=><option key={p.id} value={p.id}>{p.name} · v{p.version}{p.current?' (current)':''}</option>)}</select></label><label>Organization access<select name="status" defaultValue={w.status}><option value="active">Active</option><option value="suspended">Suspended</option></select></label><label>Subscription state<select name="subscription" defaultValue={w.subscription}><option value="active">Active</option><option value="pending">Pending</option><option value="past_due">Past due</option><option value="cancelled">Cancelled</option></select></label><label>Reason for change<input name="reason" required maxLength={500} placeholder="e.g. Additional employee allowance"/></label><label className="checkbox-label full"><input type="checkbox" checked={custom} onChange={e=>setCustom(e.target.checked)}/>Use custom allowances for this organization</label>{custom&&<>{Object.entries(allowanceLabels).map(([k,name])=><label key={k}>{name}<input name={k} type="number" min={k==='seats'?1:0} max={1000000} step={1} defaultValue={w.limits[k]} required/></label>)}<label>Override expiry (optional)<input type="datetime-local" name="expiresAt" defaultValue={w.allowanceOverride?.expiresAt?new Date(Date.parse(w.allowanceOverride.expiresAt)-new Date(w.allowanceOverride.expiresAt).getTimezoneOffset()*60000).toISOString().slice(0,16):''}/></label></>}<p className="full muted">Suspension blocks customer access while keeping provider management available. Existing records are preserved.</p></div><footer className="modal-footer"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button busy={busy}>Save organization</Button></footer></form></Modal>;
}
function PlanEdit({plan,onClose,onSave}){const[busy,setBusy]=useState(false);return <Modal wide title={`New ${plan.name} version`} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.target),data={...Object.fromEntries(Object.keys(allowanceLabels).map(k=>[k,Number(form.get(k))])),features:form.getAll('features'),reason:form.get('reason')};setBusy(true);try{await onSave(data);}finally{setBusy(false);}}}><div className="form-grid">{Object.entries(allowanceLabels).map(([k,name])=><label key={k}>{name}<input name={k} type="number" min={k==='seats'?1:0} max={1000000} step={1} required defaultValue={plan[k]}/></label>)}<label>Reason for new version<input name="reason" required maxLength={500}/></label><fieldset className="full provider-features"><legend>Included features</legend>{Object.entries(features).map(([key,name])=><label className="checkbox-label" key={key}><input type="checkbox" name="features" value={key} defaultChecked={key==='audit'||plan.features.includes(key)} disabled={key==='audit'}/>{name}</label>)}</fieldset><p className="full muted">Admin activity history is available on every plan. Existing subscriptions keep their assigned version.</p></div><footer className="modal-footer"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button busy={busy}>Create plan version</Button></footer></form></Modal>;}

export function InvitationLanding(){
 const{route,load,logout}=useApp(),[info,setInfo]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;api('invitation',{token:route.id}).then(x=>{if(active)setInfo(x);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[route.id]);
 return <div className="invitation-screen"><div className="provider-brand">vayu<span>.</span><small>YOUR ORGANIZATION INVITATION</small></div><section className="panel">{error?<><h1>Invitation unavailable</h1><p role="alert">{error}</p><Button variant="secondary" onClick={()=>go('overview')}>Back to workspace</Button></>:info?<><span className="invitation-icon"><Users size={25}/></span><h1>Join {info.organization}</h1><p>{info.name}, you’re invited as {info.role==='member'?'an employee':info.role==='admin'?'an administrator':'a guest'}.</p><dl><div><dt>Email</dt><dd>{info.email}</dd></div><div><dt>Expires</dt><dd>{date(info.expiresAt)}</dd></div></dl><div className="notice">This invitation joins a local preview identity. Production account verification and email delivery are not connected yet.</div><Button busy={busy} onClick={async()=>{setBusy(true);try{await api('invitation/accept',{token:route.id});await load();go(info.role==='guest'?'rooms':'overview');}catch(e){setError(e.message);}finally{setBusy(false);}}}>Join local organization<ChevronRight size={16}/></Button></>:<p>Loading invitation…</p>}</section></div>;
}
