import React,{useState} from 'react';
import {Plus,Copy,Users} from 'lucide-react';
import {useApp,Button,Badge,Avatar,Modal,Confirm,Empty,api,date} from './lib.jsx';

export function OrganizationTeam(){
 const{state,mutate,toast,load}=useApp(),[invite,setInvite]=useState(false),[link,setLink]=useState(''),[edit,setEdit]=useState(null),[cancel,setCancel]=useState(null),[transfer,setTransfer]=useState(false),[busy,setBusy]=useState(false);
 const counts=state.teamUsage||{active:state.usage.seats,reserved:0,guests:0,reservedGuests:0},plan=state.plans[state.workspace.plan];
 const copy=async()=>{try{await navigator.clipboard.writeText(link);toast('Invitation link copied');}catch{toast('Copy the link from the field below.','error');}};
 return <><div className="team-capacity"><span><strong>{counts.active+counts.reserved} / {plan.seats}</strong> employee seats</span><small>{counts.active} active · {counts.reserved} reserved by invitations</small><span><strong>{counts.guests+counts.reservedGuests} / {plan.guests??25}</strong> guests</span><Button variant="secondary" icon={Plus} onClick={()=>{setLink('');setInvite(true);}}>Invite employee or guest</Button></div><section className="panel"><div className="row between wrap"><div><h2>Your organization’s people</h2><p className="muted">Owners and administrators count toward the employee allowance. Provider accounts do not.</p></div>{state.provider&&<Button variant="secondary" onClick={()=>setTransfer(true)}>Transfer ownership</Button>}</div><div className="team-list">{state.users.map(u=><div key={u.id}><Avatar user={u}/><div><strong>{u.name}{u.id===state.user.id?' (you)':''}</strong><small>{u.email}</small></div><Badge>{u.disabled?'Disabled':u.id===state.workspace.ownerId?'Owner':u.role==='member'?'Employee':u.role}</Badge>{u.id!==state.user.id&&(state.provider||u.id!==state.workspace.ownerId)&&<Button variant="secondary" onClick={()=>setEdit(u)}>Manage</Button>}</div>)}</div><div className="invitation-list"><h3>Pending invitations</h3>{state.invitations?.length?state.invitations.map(i=><div key={i.id}><Users size={19}/><div><strong>{i.name}</strong><small>{i.email} · {i.role} · expires {date(i.expiresAt)}</small></div><Badge>Seat reserved</Badge><Button variant="ghost" onClick={()=>setCancel(i)}>Cancel invite</Button></div>):<p className="muted">No pending invitations.</p>}</div></section>
 {invite&&<Modal title={link?'Invitation ready':'Invite a team member'} onClose={()=>setInvite(false)}>{link?<div className="modal-body"><p>The invitation reserves a seat for seven days. Share this link with the intended person.</p><div className="invitation-link"><input aria-label="Invitation link" readOnly value={link}/><Button icon={Copy} onClick={copy}>Copy</Button></div><div className="notice">Local preview link only. No invitation email has been sent.</div><Button variant="secondary" onClick={()=>setInvite(false)}>Done</Button></div>:<form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));setBusy(true);try{const r=await mutate({action:'invitation.create',data},'Invitation created; seat reserved');if(r)setLink(`${location.origin}/#/invite/${r.token}`);}finally{setBusy(false);}}}><div className="form-grid"><label>Name<input name="name" required maxLength={100}/></label><label>Email<input name="email" type="email" required/></label><label className="full">Organization role<select name="role"><option value="member">Employee · business workflows</option><option value="admin">Admin · organization management</option><option value="guest">Guest · invited rooms only</option></select></label><p className="full muted">Creates a single-use local invitation. Active employees and pending invitations share the same plan limit.</p></div><footer className="modal-footer"><Button type="button" variant="secondary" onClick={()=>setInvite(false)}>Cancel</Button><Button busy={busy}>Create invitation</Button></footer></form>}</Modal>}
 {edit&&<Modal title={`Manage ${edit.name}`} onClose={()=>setEdit(null)}><form onSubmit={async e=>{e.preventDefault();const fields=Object.fromEntries(new FormData(e.target));setBusy(true);try{const r=await mutate({action:'member.update',entityId:edit.id,data:{name:fields.name,role:edit.id===state.workspace.ownerId?'admin':fields.role,disabled:fields.disabled==='on'}},'Employee access updated');if(r){setEdit(null);await load();}}finally{setBusy(false);}}}><div className="form-grid"><label className="full">Name<input name="name" required maxLength={100} defaultValue={edit.name}/></label><label className="full">Organization role<select name="role" disabled={edit.id===state.workspace.ownerId} defaultValue={edit.role}><option value="member">Employee</option><option value="guest">Guest</option><option value="admin">Admin</option></select></label><label className="checkbox-label full"><input name="disabled" type="checkbox" disabled={edit.id===state.workspace.ownerId} defaultChecked={edit.disabled}/>Disable access and release this seat</label>{edit.id===state.workspace.ownerId&&<p className="full muted">Transfer ownership to another administrator before disabling this owner.</p>}</div><footer className="modal-footer"><Button busy={busy}>Save employee</Button></footer></form></Modal>}
 {cancel&&<Confirm title="Cancel invitation" text={`Cancel the invitation for ${cancel.email} and release its reserved seat?`} onClose={()=>setCancel(null)} onConfirm={async()=>{if(await mutate({action:'invitation.cancel',entityId:cancel.id},'Invitation cancelled'))setCancel(null);}}/>}
 {transfer&&<Modal title="Transfer organization ownership" onClose={()=>setTransfer(false)}><form onSubmit={async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(await mutate({action:'organization.transfer',data},'Organization owner changed'))setTransfer(false);}}><div className="modal-body"><label>New owner<select required name="ownerId" defaultValue=""><option value="" disabled>Choose an active administrator</option>{state.users.filter(u=>u.role==='admin'&&!u.disabled&&u.id!==state.workspace.ownerId).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><p className="muted">The previous owner remains an administrator. This change is recorded under your provider identity.</p></div><footer className="modal-footer"><Button>Transfer ownership</Button></footer></form></Modal>}
 </>;
}
